defmodule MobCi.Build do
  @moduledoc """
  Layer 2: prepare a host app for an activated plugin set and build/install it on
  a booted device via `mix mob.deploy --native --device <serial>` (which builds
  the x86_64 APK, installs it, and pushes the OTP runtime + BEAMs in one step —
  adb push to a redroid over loopback is reliable).

  Host modes:
    * `:harness` — a throwaway app generated by `mix mob.new`, fixtures added as
      path deps + activated. The milestone-1 sample set uses this.
    * `:sloppy_joe` — the real app, activation varied over its own plugins.

  The pure construction (mob.exs / local.properties bodies, deps splice, deploy
  args, aapt permission parsing) is unit-tested; `prepare_harness/2` + `deploy/2`
  shell out (`:integration`). The exact steps below — `--dest` not `--app`, the
  mandatory `mix mob.icon`, the `acknowledge_unsafe_plugins` gate, the OTP cache
  layout — were discovered on the first real device run (2026-06-19).
  """

  alias MobCi.Plugins

  @harness_root Path.expand("../../fixtures/_harness", __DIR__)

  # The Android SDK of the machine building: the NUC's, or the Mac lane's for
  # `deploy:android_physical` (where the NUC path made mob.doctor find no NDK).
  @doc false
  @spec sdk_dir() :: Path.t()
  def sdk_dir do
    System.get_env("ANDROID_HOME") || System.get_env("ANDROID_SDK_ROOT") ||
      if(match?({:unix, :darwin}, :os.type()),
        do: Path.expand("~/Library/Android/sdk"),
        else: "/home/kevin/Android/Sdk"
      )
  end

  # The ecosystem checkout root: the NUC keeps mob, mob_dev, mob_new, every
  # plugin and sloppy_joe as siblings under ~/code (and the core three track
  # origin/master, see the 2026-10-08 decision). Explicit, not derived from
  # __DIR__, so a worktree under ~/code/mob_ci-worktrees/<slug> resolves the
  # same siblings as the main checkout.
  @ecosystem_dir Path.expand("~/code")

  @type host :: :harness | :sloppy_joe
  @type dep :: {atom(), String.t()} | {atom(), keyword()} | {atom(), String.t(), keyword()}

  @doc "The ecosystem checkout root (`~/code`)."
  @spec ecosystem_dir() :: Path.t()
  def ecosystem_dir, do: @ecosystem_dir

  @doc "Where generated harness apps live (`fixtures/_harness`)."
  @spec harness_root() :: Path.t()
  def harness_root, do: @harness_root

  @doc """
  The baseline core deps for the self-test harness: path deps on the ecosystem's
  `mob` + `mob_dev` checkouts (origin/master on the NUC), i.e. the `master` row.
  `MobCi.Versions` (MOB-413) produces the same shape for `hex`/`rc:` rows.
  """
  @spec core_deps(Path.t()) :: [dep()]
  def core_deps(ecosystem_dir \\ @ecosystem_dir) do
    [
      {:mob, path: Path.join(ecosystem_dir, "mob"), override: true},
      {:mob_dev, path: Path.join(ecosystem_dir, "mob_dev"), only: :dev, runtime: false, override: true}
    ]
  end

  @doc "One dep tuple as its mix.exs source line (data in, source out)."
  @spec render_dep(dep()) :: String.t()
  def render_dep({name, req}) when is_binary(req), do: "{#{inspect(name)}, #{inspect(req)}}"
  def render_dep({name, opts}) when is_list(opts), do: "{#{inspect(name)}, #{render_opts(opts)}}"
  def render_dep({name, req, opts}) when is_binary(req) and is_list(opts),
    do: "{#{inspect(name)}, #{inspect(req)}, #{render_opts(opts)}}"

  defp render_opts(opts), do: Enum.map_join(opts, ", ", fn {k, v} -> "#{k}: #{inspect(v)}" end)

  @doc """
  Where the host's `mob` sources live: the path dep's dir when `core_deps` pins
  `:mob` to a path, else `<host_dir>/deps/mob` (Hex/git deps are fetched there).
  Both `mob.exs` (`config :mob_dev, :mob_dir`) and `local.properties`
  (`mob.mob_dir`) must agree with this, or the native build reads a stale tree.
  """
  @spec mob_dir(Path.t(), [dep()]) :: Path.t()
  def mob_dir(host_dir, core_deps) do
    case List.keyfind(core_deps, :mob, 0) do
      {:mob, opts} when is_list(opts) -> Keyword.get(opts, :path) || Path.join(host_dir, "deps/mob")
      {:mob, _req, opts} when is_list(opts) -> Keyword.get(opts, :path) || Path.join(host_dir, "deps/mob")
      _ -> Path.join(host_dir, "deps/mob")
    end
  end

  # ── pure construction (unit-tested) ──────────────────────────────────────────

  @doc "Manifest-bearing plugins in `set` (tier-0 contributes nothing → omitted)."
  @spec activated_names([atom()]) :: [atom()]
  def activated_names(set), do: for(name <- set, is_map(Plugins.load_manifest(name)), do: name)

  @doc """
  The harness `mob.exs` body: mob_dir, the activated set, and the trust gate.
  Fixtures are unsigned local prototypes (no pubkey → acknowledged); a real,
  published plugin in the set is trusted by the fingerprint of the pubkey it
  ships under `<host_dir>/deps/<plugin>` (so write this AFTER `deps.get`).
  """
  @spec mob_exs([atom()], Path.t(), Path.t() | nil) :: String.t()
  def mob_exs(set, mob_dir, host_dir \\ nil) do
    activated = activated_names(set)

    trusted =
      if host_dir,
        do: for(p <- activated, fp = plugin_fingerprint(p, host_dir), into: %{}, do: {p, fp}),
        else: %{}

    """
    import Config

    config :mob_dev,
      mob_dir: #{inspect(mob_dir)},
      elixir_lib:
        System.get_env("MOB_ELIXIR_LIB", :code.lib_dir(:elixir) |> to_string() |> Path.dirname())

    config :mob, :plugins, #{inspect(activated)}

    # Signed (published) plugins are trusted by their shipped pubkey; the unsigned
    # fixtures are acknowledged past the trust gate.
    config :mob, :trusted_plugins, #{inspect(trusted)}
    config :mob, :acknowledge_unsafe_plugins, #{inspect(activated)}
    """
  end

  @doc """
  The `defp deps do … end` block: `core_deps` (mob + mob_dev, see `core_deps/1`)
  followed by ecto and the activated plugins — a fixture as a path dep, a real
  plugin as its latest Hex release (`>= 0.0.0`, the `hex` row; what a user gets).
  """
  @spec deps_block([atom()], Path.t(), [dep()]) :: String.t()
  def deps_block(set, harness_dir, core_deps \\ core_deps()) do
    plugin_deps = for name <- activated_names(set), do: "      " <> render_dep(plugin_dep(name, harness_dir))

    palette =
      if :mob_ci_palette in set,
        do: ["      " <> render_dep(plugin_dep(:mob_ci_palette, harness_dir))],
        else: []

    lines =
      Enum.map(core_deps, &("      " <> render_dep(&1))) ++
        ["      {:ecto_sqlite3, \"~> 0.18\"}"] ++ palette ++ plugin_deps

    "  defp deps do\n    [\n" <> Enum.join(lines, ",\n") <> "\n    ]\n  end"
  end

  @doc """
  The real plugins a host has fetched under `deps/` (those with a manifest),
  plugin → dir: what `Plugins.put_resolved_dirs/1` gets so the invariants read
  the manifest of the version the host actually built, not the `~/code` sibling.
  """
  @spec fetched_plugin_dirs(Path.t()) :: %{atom() => Path.t()}
  def fetched_plugin_dirs(host_dir) do
    for dir <- Path.wildcard(Path.join(host_dir, "deps/mob_*")),
        File.exists?(Path.join(dir, "priv/mob_plugin.exs")),
        into: %{},
        do: {String.to_atom(Path.basename(dir)), dir}
  end

  @doc "A plugin's dep tuple for a harness at `harness_dir`: fixture → relative path dep; real → latest Hex."
  @spec plugin_dep(atom(), Path.t()) :: dep()
  def plugin_dep(name, harness_dir) do
    if Plugins.fixture?(name),
      do: {name, path: Path.relative_to(Plugins.fixture_dir(name), harness_dir)},
      else: {name, ">= 0.0.0"}
  end

  @doc "Android `local.properties` body (sdk + OTP cache paths + mob_dir)."
  @spec local_properties(Path.t()) :: String.t()
  def local_properties(mob_dir) do
    %{base: base, arm32: arm32, x86_64: x86} = otp_paths()

    """
    sdk.dir=#{sdk_dir()}
    mob.otp_release=#{base}
    mob.otp_release_arm32=#{arm32}
    mob.otp_release_x86_64=#{x86}
    mob.mob_dir=#{mob_dir}
    """
  end

  @doc "The Android package mob.new derives for an app: `com.example.<app>`."
  @spec package_name(atom() | String.t()) :: String.t()
  def package_name(app), do: "com.example.#{app}"

  @sloppy_joe_dir Path.join(@ecosystem_dir, "sloppy_joe")

  @doc "Where the real sloppy_joe checkout lives (`~/code/sloppy_joe`)."
  @spec sloppy_joe_dir() :: Path.t()
  def sloppy_joe_dir, do: @sloppy_joe_dir

  @doc """
  mob.exs body for the sloppy_joe gate: activate `subset` and clear the signature
  gate for it. First-party plugins are inconsistently signed AND signed with
  *different* keys (F3: mob_touch/mob_video share one key, mob_bluetooth a
  rotated/distinct one, others unsigned) — so a single pinned fingerprint trips
  the gate's key-rotation check for any plugin not on that one key. Instead derive
  each signed plugin's REAL fingerprint from its shipped `priv/mob_plugin.pub`
  (the exact value `SignatureGate.check_trust` compares against) and trust that.
  Unsigned plugins ship no pubkey, drop out of `trusted_plugins`, and are cleared
  via `acknowledge_unsafe_plugins` instead. Every plugin is listed in BOTH lists'
  union of effect, harmless for whichever path doesn't apply.
  """
  @spec sloppy_joe_mob_exs([atom()], Path.t()) :: String.t()
  def sloppy_joe_mob_exs(subset, dir \\ @sloppy_joe_dir) do
    trusted = for p <- subset, fp = plugin_fingerprint(p, dir), into: %{}, do: {p, fp}

    """
    import Config

    config :mob_dev, mob_dir: "#{Path.join(dir, "deps/mob")}"

    config :mob, :plugins, #{inspect(subset)}
    config :mob, :trusted_plugins, #{inspect(trusted)}
    config :mob, :acknowledge_unsafe_plugins, #{inspect(subset)}
    """
  end

  @doc """
  The signed-plugin trust fingerprint the gate will compute for `plugin`:
  `"ed25519:" <> base64(sha256(raw 32-byte pubkey))` from its `priv/mob_plugin.pub`
  (mirrors `MobDev.Plugin.{Verify.load_pubkey, Crypto.fingerprint}`). The pubkey
  is read from the host's `deps/<plugin>` (Hex/git deps) or, for a path dep (Mix
  never copies those into `deps/`), from the ecosystem checkout `~/code/<plugin>`.
  `nil` for an unsigned plugin (no/blank/malformed pubkey): it isn't trusted; the
  acknowledge_unsafe path clears it instead.
  """
  @spec plugin_fingerprint(atom(), Path.t()) :: String.t() | nil
  def plugin_fingerprint(plugin, host_dir \\ @sloppy_joe_dir) do
    [Path.join([host_dir, "deps", to_string(plugin)]), Path.join(@ecosystem_dir, to_string(plugin))]
    |> Enum.map(&Path.join(&1, "priv/mob_plugin.pub"))
    |> Enum.find_value(&fingerprint_of_pubkey_file/1)
  end

  defp fingerprint_of_pubkey_file(path) do
    with {:ok, contents} <- File.read(path),
         {:ok, pub} when byte_size(pub) == 32 <- Base.decode64(String.trim(contents)) do
      "ed25519:" <> Base.encode64(:crypto.hash(:sha256, pub))
    else
      _ -> nil
    end
  end

  @doc """
  The `mob_*` plugin deps declared in a mix.exs body (`{:mob_x, "~> 1.0"}`,
  `{:mob_x, path: …}`), in declaration order; `:mob` and `:mob_dev` are the
  runtime/tooling, not plugins. Pure: the realism set is whatever the app
  declares today, never a list mob_ci has to keep in sync by hand.
  """
  @spec plugin_deps(String.t()) :: [atom()]
  def plugin_deps(mix_exs_body) do
    ~r/^\s*\{:(mob_[a-z0-9_]+),/m
    |> Regex.scan(mix_exs_body, capture: :all_but_first)
    |> Enum.map(fn [name] -> String.to_atom(name) end)
    |> Enum.reject(&(&1 == :mob_dev))
  end

  @doc "sloppy_joe's real plugin set (read from its mix.exs) — the realism gate's full activation."
  @spec sloppy_joe_plugins() :: [atom()]
  def sloppy_joe_plugins, do: @sloppy_joe_dir |> Path.join("mix.exs") |> File.read!() |> plugin_deps()

  @doc """
  Rewrite absolute `path:` deps that don't exist on this machine to the sibling
  checkout under `ecosystem_dir` (F7: sloppy_joe commits Mac-absolute
  `/Users/kevin/code/<repo>` path deps, which no other host can resolve). A path
  that exists, or whose basename has no sibling here, is left alone. `exists?`
  is injectable so the rewrite is unit-testable without those directories.
  """
  @spec relocate_path_deps(String.t(), Path.t(), (Path.t() -> boolean())) :: String.t()
  def relocate_path_deps(mix_exs_body, ecosystem_dir, exists? \\ &File.dir?/1) do
    Regex.replace(~r/path: "([^"]+)"/, mix_exs_body, fn whole, path ->
      sibling = Path.join(ecosystem_dir, Path.basename(path))

      cond do
        exists?.(path) -> whole
        exists?.(sibling) -> ~s(path: "#{sibling}")
        true -> whole
      end
    end)
  end

  @doc "Android package for a host: sloppy_joe has its own; the harness uses com.example.<app>."
  @spec host_package(:sloppy_joe | :harness, atom()) :: String.t()
  def host_package(:sloppy_joe, _app), do: "com.genericjam.sloppyjoe"
  def host_package(:harness, app), do: package_name(app)

  @doc """
  Prepare the real sloppy_joe app to build with `subset` activated. Builds
  **in place** (reusing its deps + build cache) by transiently swapping its
  gitignored `mob.exs` and relocating its machine-absolute path deps (F7), then
  `mix deps.get` so the lock's plugin versions are present; returns a `:cleanup`
  thunk the caller MUST run to restore both files. The carrier dial-out
  (`mcp.sloppyjoe.ca`) is left intact — a CI build dials in as a transient,
  unclaimable device that teardown reaps (it has no `kind:"staging"` row so the
  live Pool can't lease it); clean suppression is a follow-up via
  `SLOPPY_JOE_PROXY_WS`.
  """
  @spec prepare_sloppy_joe([atom()]) ::
          {:ok, %{dir: Path.t(), app: atom(), pkg: String.t(), cleanup: (-> any())}} | {:error, term()}
  def prepare_sloppy_joe(subset) do
    dir = @sloppy_joe_dir
    mob_exs_path = Path.join(dir, "mob.exs")
    mix_exs_path = Path.join(dir, "mix.exs")

    if File.dir?(dir) do
      original_mob_exs = File.read!(mob_exs_path)
      original_mix_exs = File.read!(mix_exs_path)
      clean_before = clean_tracked(dir)

      cleanup = fn ->
        File.write!(mob_exs_path, original_mob_exs)
        File.write!(mix_exs_path, original_mix_exs)
        # The deploy regenerates tracked files (priv/generated/*, the plugin
        # Kotlin bridge copies): leave the shared checkout exactly as we found
        # it (only the paths that were clean before).
        for path <- clean_before, do: System.cmd("git", ["-C", dir, "checkout", "--", path], stderr_to_stdout: true)
      end

      File.write!(mix_exs_path, relocate_path_deps(original_mix_exs, @ecosystem_dir))
      File.write!(mob_exs_path, sloppy_joe_mob_exs(subset, dir))

      case sh(["deps.get"], dir) do
        {_out, 0} ->
          Plugins.put_resolved_dirs(fetched_plugin_dirs(dir))
          {:ok, %{dir: dir, app: :sloppy_joe, pkg: host_package(:sloppy_joe, :sloppy_joe), cleanup: cleanup}}

        {out, code} ->
          cleanup.()
          {:error, {:sloppy_joe_prep, code, String.slice(out, -600, 600)}}
      end
    else
      {:error, {:sloppy_joe_missing, dir}}
    end
  end

  # Tracked trees a native build regenerates; the ones clean right now are restored on cleanup.
  @regenerated_paths ["priv/generated", "android/app/src/main/java/io/mob"]
  defp clean_tracked(dir) do
    for path <- @regenerated_paths,
        match?({"", 0}, System.cmd("git", ["-C", dir, "status", "--porcelain", "--", path], stderr_to_stdout: true)),
        do: path
  end

  @doc "The generated showcase screen module for P5: `<AppModule>.CiShowcase`."
  @spec showcase_module(atom()) :: module()
  def showcase_module(app), do: Module.concat([Macro.camelize(to_string(app)), CiShowcase])

  @doc "Activated plugins that contribute a UI component, with their widget module + id (P5)."
  @spec component_widgets([atom()]) :: [{module(), atom()}]
  def component_widgets(set) do
    # Only the fixtures follow the `<Plugin>.widget(id:)` convention the showcase
    # relies on; a real plugin's component has no generic embedding (P5 skips it).
    for name <- activated_names(set),
        Plugins.fixture?(name),
        m = Plugins.load_manifest(name),
        comps = Map.get(m, :ui_components, []),
        comps != [],
        comp = hd(comps),
        atom = comp[:atom] do
      {Module.concat([Macro.camelize(to_string(name))]), atom}
    end
  end

  @doc """
  Source for a screen embedding every activated component's widget — what P5
  pushes to confirm components render without a dispatch crash. With no
  components the screen is a plain label (P5 then skips on an empty set).
  """
  @spec showcase_source([atom()], atom()) :: String.t()
  def showcase_source(set, app) do
    widgets =
      case component_widgets(set) do
        [] -> ~s(      <Text text="no components" text_color={:on_surface} />)
        ws -> Enum.map_join(ws, "\n", fn {mod, id} -> "      {#{inspect(mod)}.widget(id: :#{id})}" end)
      end

    """
    defmodule #{inspect(showcase_module(app))} do
      @moduledoc "Generated by mob_ci — embeds every activated UI component for P5."
      use Mob.Screen

      def mount(_params, _session, socket), do: {:ok, socket}

      def render(_assigns) do
        ~MOB\"""
        <Scroll background={:background}>
          <Column background={:background} padding={:space_lg}>
    #{widgets}
          </Column>
        </Scroll>
        \"""
      end
    end
    """
  end

  @doc "A deterministic harness app name for a set (stable → reuses the build cache)."
  @spec harness_app_name([atom()]) :: atom()
  def harness_app_name(set) do
    if Enum.sort(set) == Enum.sort(Plugins.sample_set()),
      do: :mob_ci_harness,
      else: :"mob_ci_h_#{:erlang.phash2(Enum.sort(set))}"
  end

  @doc "Args for the native x86_64 deploy to a specific device serial."
  @spec deploy_args(String.t()) :: [String.t()]
  def deploy_args(serial), do: ["mob.deploy", "--native", "--device", serial]

  @doc "Parse `aapt dump permissions <apk>` into the declared permission set (P6 actual side)."
  @spec parse_permissions(String.t()) :: MapSet.t(String.t())
  def parse_permissions(aapt_output) do
    ~r/uses-permission: name='([^']+)'/
    |> Regex.scan(aapt_output, capture: :all_but_first)
    |> Enum.map(fn [p] -> p end)
    |> MapSet.new()
  end

  # Resolve the OTP cache triple (base/arm32/x86_64) from a single discovered hash.
  defp otp_paths do
    cache = Path.expand("~/.mob/cache")

    hash =
      case Path.wildcard(Path.join(cache, "otp-android-x86_64-*")) do
        [dir | _] -> dir |> Path.basename() |> String.replace_prefix("otp-android-x86_64-", "")
        [] -> nil
      end

    %{
      base: Path.join(cache, "otp-android-#{hash}"),
      arm32: Path.join(cache, "otp-android-arm32-#{hash}"),
      x86_64: Path.join(cache, "otp-android-x86_64-#{hash}")
    }
  end

  # ── exec (integration) ───────────────────────────────────────────────────────

  @doc """
  Prepare the harness for `set`: generate (or reuse) the app, wire fixtures, write
  mob.exs + local.properties, fetch deps, and generate icons. Returns
  `{:ok, %{dir, app, pkg}}`. `reuse: true` (default) keeps an existing prepared
  dir to preserve the gradle/_build cache; `fresh: true` regenerates from scratch.
  """
  @spec prepare_harness([atom()], keyword()) ::
          {:ok, %{dir: Path.t(), app: atom(), pkg: String.t()}} | {:error, term()}
  def prepare_harness(set, opts \\ []) do
    app = harness_app_name(set)
    dir = Path.join(@harness_root, to_string(app))
    pkg = package_name(app)
    reuse = Keyword.get(opts, :reuse, true) and not Keyword.get(opts, :fresh, false)

    result =
      if reuse and reusable?(dir, set) do
        {:ok, %{dir: dir, app: app, pkg: pkg}}
      else
        generate_harness(set, dir, app, pkg)
      end

    # Always (re)write mob.exs (activation + trust fingerprints from the fetched
    # deps) and the P5 showcase screen — cheap, and keeps both in sync with the
    # activated set even when the harness dir is reused.
    with {:ok, %{dir: d}} <- result do
      activate(d, set, app)
    end

    result
  end

  defp generate_harness(set, dir, app, pkg) do
    File.rm_rf!(dir)
    File.mkdir_p!(@harness_root)
    mob_dir = mob_dir(dir, core_deps())

    with {_o, 0} <- sh(mob_new_args(app), @harness_root),
         :ok <- splice_deps(dir, set),
         :ok <- File.write(Path.join(dir, "android/local.properties"), local_properties(mob_dir)),
         {_o2, 0} <- sh(["deps.get"], dir),
         :ok <- activate(dir, set, app),
         {_o3, 0} <- sh(["mob.icon"], dir) do
      {:ok, %{dir: dir, app: app, pkg: pkg}}
    else
      {out, code} when is_integer(code) -> {:error, {:harness_prep, code, String.slice(out, -600, 600)}}
      {:error, _} = err -> err
    end
  end

  @doc """
  Can a prepared harness dir be reused as-is? Only when its mix.exs still
  carries exactly the deps block we would generate now — a harness generated
  against other core deps (the June `mob_dev == 0.6.5` pin, or a different
  version row) is stale and must be regenerated, or the run silently tests the
  wrong mob_dev.
  """
  @spec reusable?(Path.t(), [atom()], [dep()]) :: boolean()
  def reusable?(dir, set, core_deps \\ core_deps()) do
    case File.read(Path.join(dir, "mix.exs")) do
      {:ok, body} -> File.exists?(Path.join(dir, "mob.exs")) and String.contains?(body, deps_block(set, dir, core_deps))
      _ -> false
    end
  end

  @doc """
  Prepare ONE harness depending on the whole `pool` (default the device pool), for
  the sweep: activation is then varied per subset via `activate/2` while the
  gradle/zig cache is shared, so each subset rebuilds in ~minutes not ~10min.
  """
  @spec prepare_sweep_harness(keyword()) ::
          {:ok, %{dir: Path.t(), app: atom(), pkg: String.t()}} | {:error, term()}
  def prepare_sweep_harness(opts \\ []) do
    pool = Keyword.get(opts, :pool, MobCi.Sweep.device_pool())
    app = :mob_ci_sweep
    dir = Path.join(@harness_root, to_string(app))
    pkg = package_name(app)
    reuse = Keyword.get(opts, :reuse, true) and not Keyword.get(opts, :fresh, false)

    result =
      if reuse and reusable?(dir, pool) do
        {:ok, %{dir: dir, app: app, pkg: pkg}}
      else
        generate_sweep_harness(dir, app, pkg, pool)
      end

    # Always (re)write local.properties — it's machine-specific config mob.new
    # ships as placeholders, and the reuse path would otherwise keep stale paths.
    with {:ok, %{dir: d}} <- result do
      File.write!(Path.join(d, "android/local.properties"), local_properties(mob_dir(d, core_deps())))
    end

    result
  end

  defp generate_sweep_harness(dir, app, pkg, pool) do
    File.rm_rf!(dir)
    File.mkdir_p!(@harness_root)

    with {_o, 0} <- sh(mob_new_args(app), @harness_root),
         :ok <- File.write(Path.join(dir, "mix.exs"), patch_deps_for(dir, pool)),
         {_o2, 0} <- sh(["deps.get"], dir),
         :ok <- activate(dir, pool, app),
         {_o3, 0} <- sh(["mob.icon"], dir) do
      {:ok, %{dir: dir, app: app, pkg: pkg}}
    else
      {out, code} when is_integer(code) -> {:error, {:sweep_harness_prep, code, String.slice(out, -600, 600)}}
      {:error, _} = err -> err
    end
  end

  @doc """
  `mix mob.new` args for a harness: Android-only and `--blank`. The default
  template is the showcase app, whose screens import mob_mishka components and
  the other showcase plugins; once `deps_block/3` replaces its deps with the
  set under test, that app no longer compiles (mob_new 0.6.7). The harness is
  a host for the plugins under test, nothing else.
  """
  @spec mob_new_args(atom()) :: [String.t()]
  def mob_new_args(app), do: ["mob.new", to_string(app), "--dest", @harness_root, "--android", "--blank"]

  defp patch_deps_for(dir, pool) do
    {:ok, body} = File.read(Path.join(dir, "mix.exs"))
    Regex.replace(~r/  defp deps do\n.*?\n  end/s, body, deps_block(pool, dir), global: false)
  end

  @doc "Set the activated subset on a prepared harness: rewrite mob.exs (activation + trust) and the showcase."
  @spec activate(Path.t(), [atom()], atom()) :: :ok
  def activate(dir, subset, app \\ :mob_ci_sweep) do
    Plugins.put_resolved_dirs(fetched_plugin_dirs(dir))
    File.write!(Path.join(dir, "mob.exs"), mob_exs(subset, mob_dir(dir, core_deps()), dir))
    File.mkdir_p!(Path.join(dir, "lib/#{app}"))
    File.write!(Path.join(dir, "lib/#{app}/ci_showcase.ex"), showcase_source(subset, app))
    :ok
  end

  # Replace the generated `defp deps do … end` (default showcase plugins) with ours.
  defp splice_deps(dir, set) do
    mix_exs = Path.join(dir, "mix.exs")

    case File.read(mix_exs) do
      {:ok, body} ->
        patched = Regex.replace(~r/  defp deps do\n.*?\n  end/s, body, deps_block(set, dir), global: false)
        File.write(mix_exs, patched)

      err ->
        err
    end
  end

  @doc """
  Build + install + push to `serial` via `mix mob.deploy --native --device`.
  Returns `:ok`, `{:conflict, msgs}` (cross-plugin rejection at validate → P1's
  expected path), or `{:error, reason}`. `log: path` keeps the complete deploy
  output (the error tuple carries only its tail).
  """
  @spec deploy(Path.t(), String.t(), keyword()) :: :ok | {:conflict, [String.t()]} | {:error, term()}
  def deploy(dir, serial, opts \\ []) do
    {out, code} = sh(deploy_args(serial), dir)

    if log = Keyword.get(opts, :log) do
      File.mkdir_p!(Path.dirname(log))
      File.write!(log, out)
    end

    if code == 0, do: :ok, else: classify_failure(out)
  end

  # What the JVM prints when it crashes under the build (the Gradle wrapper or
  # its daemon): its fatal-error banner, or the hs_err report path.
  @jvm_crash_patterns [
    ~r/A fatal error has been detected by the Java Runtime Environment/,
    ~r/hs_err_pid\d+\.log/
  ]

  # The lines of a JVM crash worth keeping as the failure's evidence.
  @jvm_crash_lines ~r/A fatal error has been detected|\b(SIGSEGV|SIGBUS|SIGILL)\b|Problematic frame|^#\s+[CjJV]\s+\[|hs_err_pid\d+\.log/

  @doc """
  Name the cause of a failed deploy from its output: a cross-plugin rejection
  (`{:conflict, lines}`, P1's expected path), a refused plugin signature
  (`{:error, {:signature_gate, lines}}` — the lines naming each plugin), a zig
  toolchain mismatch (`{:error, {:toolchain, line}}`), a JVM crash under
  Gradle (`{:error, {:jvm_crash, lines}}`: the banner, signal, frame and
  hs_err lines, read from the whole output since the tail kept otherwise may
  have lost them), else the native build's tail. Pure, so each shape is
  pinned by a test.
  """
  @spec classify_failure(String.t()) :: {:conflict, [String.t()]} | {:error, term()}
  def classify_failure(out) do
    cond do
      out =~ "declare the same" or out =~ "capability check failed" ->
        {:conflict, conflict_lines(out)}

      out =~ "plugin signature check failed" ->
        {:error, {:signature_gate, lines_matching(out, ~r/^\s*- plugin :\w+/)}}

      out =~ "zig version mismatch" ->
        {:error, {:toolchain, lines_matching(out, ~r/zig version mismatch/) |> List.first()}}

      # lost-device lines stay too, so `farm` still takes precedence (Run.error_layer/1)
      toolchain_crash?(out) ->
        lines = for l <- String.split(out, "\n"), l =~ @jvm_crash_lines or MobCi.Farm.lost_device?(l), do: String.trim(l)
        {:error, {:jvm_crash, lines}}

      true ->
        {:error, {:native_build, String.slice(out, -800, 800)}}
    end
  end

  defp lines_matching(out, regex) do
    out |> String.split("\n") |> Enum.filter(&Regex.match?(regex, &1)) |> Enum.map(&String.trim/1)
  end

  defp conflict_lines(out) do
    out
    |> String.split("\n")
    |> Enum.filter(&(&1 =~ "declare the same" or &1 =~ "capability"))
    |> Enum.map(&String.trim/1)
  end

  @doc """
  The plugin mob_dev named in a classified build failure, when it named one:
  the first plugin of a signature-gate refusal, else the first
  `plugin :mob_x` in the output tail (mob_dev's wording for every per-plugin
  build error), else the first `deps/mob_x/` source path a compiler error
  points into. nil when the failure names no plugin (toolchain, gradle).
  """
  @spec failing_plugin(term()) :: atom() | nil
  def failing_plugin({:signature_gate, lines}) when is_list(lines), do: first_plugin(Enum.join(lines, "\n"))
  def failing_plugin({:native_build, tail}) when is_binary(tail), do: first_plugin(tail)
  def failing_plugin({:release_build, tail}) when is_binary(tail), do: first_plugin(tail)
  def failing_plugin(_reason), do: nil

  defp first_plugin(text) do
    named = Regex.run(~r/plugin :(mob_[a-z0-9_]+)/, text, capture: :all_but_first)

    path =
      ~r{deps/(mob_[a-z0-9_]+)/}
      |> Regex.scan(text, capture: :all_but_first)
      |> List.flatten()
      |> Enum.reject(&(&1 in ["mob_dev", "mob_new"]))

    case named || path do
      [name | _] -> String.to_atom(name)
      _ -> nil
    end
  end

  # ── the release path (`mix mob.release --android`, MOB-414) ──────────────────

  @doc """
  A cell's build-path label: `:deploy` is the dev APK `mix mob.deploy
  --native` installs, `:release` the `mix mob.release --android` bundle.
  """
  @spec path_label(:deploy | :release) :: String.t()
  def path_label(:deploy), do: "deploy:android"
  def path_label(:release), do: "release:android"

  @doc """
  The layer of a build path that failed outright: `build:<path>`, or
  `build:<path>/<plugin>` when mob_dev's output named the failing plugin
  (`failing_plugin/1`).
  """
  @spec path_failure_layer(:deploy | :release, term()) :: MobCi.Result.layer()
  def path_failure_layer(path, reason) do
    case failing_plugin(reason) do
      nil -> {:build, path_label(path)}
      plugin -> {:build, path_label(path), plugin}
    end
  end

  @doc """
  Did the build's toolchain itself crash (a JVM fatal error under Gradle)?
  Such a build says nothing about the code under test: layer `toolchain`.
  """
  @spec toolchain_crash?(term()) :: boolean()
  def toolchain_crash?(reason) do
    text = if is_binary(reason), do: reason, else: inspect(reason, limit: :infinity, printable_limit: :infinity)
    Enum.any?(@jvm_crash_patterns, &Regex.match?(&1, text))
  end

  # A throwaway upload key for hosts that have no signing config of their own:
  # the release path signs exactly as a user's does (android/keystore.properties
  # → upload_jks.keystore, alias upload, JKS — the shape `mix mob.google_play`
  # writes); the key never leaves the (gitignored) generated host dir.
  @release_keystore "upload_jks.keystore"
  @release_key_alias "upload"
  @release_key_pass "mob_ci_release"

  @type signing :: %{ks: Path.t(), alias: String.t(), store_pass: String.t(), key_pass: String.t()}

  @doc "The `android/keystore.properties` body for the CI upload key."
  @spec keystore_properties() :: String.t()
  def keystore_properties do
    """
    storeFile=#{@release_keystore}
    storePassword=#{@release_key_pass}
    keyAlias=#{@release_key_alias}
    keyPassword=#{@release_key_pass}
    """
  end

  @doc """
  Parse an `android/keystore.properties` body (what the generated
  `build.gradle` reads: `storeFile` relative to `android/`, `storePassword`,
  `keyAlias`, `keyPassword`) into the signing bundletool needs.
  """
  @spec parse_keystore_properties(String.t(), Path.t()) :: {:ok, signing()} | {:error, term()}
  def parse_keystore_properties(body, android_dir) do
    props =
      for line <- String.split(body, "\n"),
          line = String.trim(line),
          line != "" and not String.starts_with?(line, "#"),
          [k, v] <- [String.split(line, "=", parts: 2)],
          into: %{},
          do: {String.trim(k), String.trim(v)}

    case props do
      %{"storeFile" => file, "storePassword" => sp, "keyAlias" => a, "keyPassword" => kp} ->
        {:ok, %{ks: Path.expand(file, android_dir), alias: a, store_pass: sp, key_pass: kp}}

      _ ->
        {:error, {:keystore_properties, "needs storeFile, storePassword, keyAlias and keyPassword"}}
    end
  end

  @doc "`keytool` args creating the CI upload key at `path`."
  @spec keytool_args(Path.t()) :: [String.t()]
  def keytool_args(path) do
    ~w(-genkeypair -keystore #{path} -storetype JKS -alias #{@release_key_alias} -keyalg RSA
       -keysize 2048 -validity 10000 -storepass #{@release_key_pass} -keypass #{@release_key_pass}
       -dname CN=mob_ci)
  end

  @doc """
  The release signing of a host: its own `android/keystore.properties` when it
  has one (read, never rewritten — a real app's upload key stays its own),
  else the CI upload key, created with its keystore.properties on first use.
  """
  @spec release_signing(Path.t()) :: {:ok, signing()} | {:error, term()}
  def release_signing(dir) do
    android = Path.join(dir, "android")
    props = Path.join(android, "keystore.properties")
    ks = Path.join(android, @release_keystore)

    cond do
      File.exists?(props) ->
        parse_keystore_properties(File.read!(props), android)

      File.exists?(ks) ->
        {:error, {:keystore_properties, "#{ks} exists without keystore.properties; not overwriting it"}}

      true ->
        with :ok <- keytool(ks), :ok <- File.write(props, keystore_properties()) do
          parse_keystore_properties(keystore_properties(), android)
        end
    end
  end

  defp keytool(ks) do
    case run(System.find_executable("keytool") || "keytool", keytool_args(ks)) do
      {:ok, _} -> :ok
      {:error, reason} -> {:error, {:keytool, reason}}
    end
  end

  @doc "Where the release AAB lands (`mix mob.release --android` output)."
  @spec release_aab(Path.t()) :: Path.t()
  def release_aab(dir), do: Path.join(dir, "android/app/build/outputs/bundle/release/app-release.aab")

  @doc """
  Build the host's release bundle with `mix mob.release --android` and turn it
  into one installable universal APK (`bundletool build-apks --mode=universal`,
  signed with the host's upload key, `release_signing/1`). `log: path` keeps
  the release build's complete output. Returns `{:ok, apk}`, or the failure
  classified as `classify_failure/1` does (a release that fails with output
  naming no known cause is `{:error, {:release_build, tail}}`).
  """
  @spec build_release(Path.t(), keyword()) :: {:ok, Path.t()} | {:conflict, [String.t()]} | {:error, term()}
  def build_release(dir, opts \\ []) do
    with {:ok, signing} <- release_signing(dir),
         :ok <- mob_release(dir, Keyword.get(opts, :log)) do
      universal_apk(dir, signing)
    end
  end

  defp mob_release(dir, log) do
    before = aab_mtime(dir)
    {out, code} = sh(["mob.release", "--android"], dir)

    if log do
      File.mkdir_p!(Path.dirname(log))
      File.write!(log, out)
    end

    cond do
      code != 0 -> classify_release_failure(out)
      # A leftover bundle from an earlier build must not pass for this one.
      aab_mtime(dir) in [nil, before] -> {:error, {:release_build, "mob.release exited 0 but wrote no new #{release_aab(dir)}"}}
      true -> :ok
    end
  end

  defp aab_mtime(dir) do
    case File.stat(release_aab(dir), time: :posix) do
      {:ok, %{mtime: mtime}} -> mtime
      _ -> nil
    end
  end

  @doc """
  `classify_failure/1` for the release build: the same conflict, signature
  and toolchain shapes; anything else is `{:release_build, tail}`.
  """
  @spec classify_release_failure(String.t()) :: {:conflict, [String.t()]} | {:error, term()}
  def classify_release_failure(out) do
    case classify_failure(out) do
      {:error, {:native_build, tail}} -> {:error, {:release_build, tail}}
      other -> other
    end
  end

  @bundletool_version "1.18.3"

  @doc """
  The bundletool jar: `$MOB_CI_BUNDLETOOL`, else
  `~/.local/share/mob_ci/bundletool-all-#{@bundletool_version}.jar`
  (downloaded from the google/bundletool release on first use).
  """
  @spec bundletool_jar() :: Path.t()
  def bundletool_jar do
    System.get_env("MOB_CI_BUNDLETOOL") ||
      Path.expand("~/.local/share/mob_ci/bundletool-all-#{@bundletool_version}.jar")
  end

  @doc "`java` args turning `aab` into a universal `.apks` set signed with `signing`."
  @spec bundletool_args(Path.t(), Path.t(), Path.t(), signing()) :: [String.t()]
  def bundletool_args(jar, aab, apks, signing) do
    [
      "-jar", jar, "build-apks", "--mode=universal", "--overwrite",
      "--bundle=#{aab}", "--output=#{apks}",
      "--ks=#{signing.ks}", "--ks-key-alias=#{signing.alias}",
      "--ks-pass=pass:#{signing.store_pass}", "--key-pass=pass:#{signing.key_pass}"
    ]
  end

  defp universal_apk(dir, signing) do
    out = Path.join(dir, "_build/mob_ci_release")
    File.mkdir_p!(out)
    apks = Path.join(out, "app-release.apks")

    with {:ok, jar} <- ensure_bundletool(),
         {:ok, _} <- run(System.find_executable("java") || "java", bundletool_args(jar, release_aab(dir), apks, signing)),
         {:ok, [apk]} <- :zip.unzip(String.to_charlist(apks), file_list: [~c"universal.apk"], cwd: String.to_charlist(out)) do
      {:ok, to_string(apk)}
    else
      {:ok, []} -> {:error, {:bundletool, "no universal.apk in #{apks}"}}
      {:error, reason} -> {:error, {:bundletool, reason}}
    end
  end

  defp ensure_bundletool do
    jar = bundletool_jar()

    if File.exists?(jar) do
      {:ok, jar}
    else
      url =
        "https://github.com/google/bundletool/releases/download/#{@bundletool_version}/bundletool-all-#{@bundletool_version}.jar"

      File.mkdir_p!(Path.dirname(jar))

      case run("curl", ["-fsSL", "-o", jar <> ".part", url]) do
        {:ok, _} -> with(:ok <- File.rename(jar <> ".part", jar), do: {:ok, jar})
        err -> err
      end
    end
  end

  @doc "Locate the harness's built debug APK (for P6 permission reading)."
  @spec locate_apk(Path.t()) :: {:ok, Path.t()} | {:error, :apk_not_found}
  def locate_apk(dir) do
    case Path.wildcard(Path.join(dir, "android/app/build/outputs/apk/**/*.apk")) do
      [apk | _] -> {:ok, apk}
      [] -> {:error, :apk_not_found}
    end
  end

  @doc "Read an APK's declared permissions via aapt (P6 actual side)."
  @spec read_permissions(Path.t()) :: {:ok, MapSet.t(String.t())} | {:error, term()}
  def read_permissions(apk) do
    case aapt(["dump", "permissions", apk]) do
      {:ok, out} -> {:ok, parse_permissions(out)}
      {:error, _} = err -> err
    end
  end

  defp aapt(args) do
    bin =
      System.find_executable("aapt") ||
        (Path.wildcard(Path.join(sdk_dir(), "build-tools/*/aapt")) |> Enum.sort() |> List.last())

    if is_nil(bin), do: {:error, :aapt_not_found}, else: run(bin, args)
  end

  @doc """
  Environment for every `mix` we run inside a host app. zig is pinned to exactly
  what the mob_dev under test requires (`MobDev.Toolchain.required_zig_version/0`,
  an exact-match check that fails the native build otherwise): a host's own
  `.tool-versions` (sloppy_joe pins no zig; mob.new's template pins a different
  nightly), mob_ci's, or whatever `mise activate` put on PATH for the caller's
  cwd must not decide which zig mob_dev's build gets. So the required version's
  install dir (`mise where zig@<v>`) goes FIRST on PATH, and `MISE_ZIG_VERSION`
  covers the shim path too. Without mise (or the version not installed) the
  env override alone is passed and the build's own check reports the mismatch.
  """
  @spec build_env() :: [{String.t(), String.t()}]
  def build_env do
    zig = MobDev.Toolchain.required_zig_version()
    env = [{"MIX_ENV", "dev"}, {"MISE_ZIG_VERSION", zig}]

    case zig_bin_dir(zig) do
      nil -> env
      bin -> [{"PATH", bin <> ":" <> (System.get_env("PATH") || "")} | env]
    end
  end

  defp zig_bin_dir(version) do
    with mise when is_binary(mise) <- System.find_executable("mise"),
         {out, 0} <- System.cmd(mise, ["where", "zig@" <> version], stderr_to_stdout: true),
         bin = Path.join(String.trim(out), "bin"),
         true <- File.exists?(Path.join(bin, "zig")) do
      bin
    else
      _ -> nil
    end
  end

  defp sh(args, cd), do: System.cmd("mix", args, cd: cd, stderr_to_stdout: true, env: build_env())

  defp run(bin, args) do
    case System.cmd(bin, args, stderr_to_stdout: true) do
      {out, 0} -> {:ok, out}
      {out, code} -> {:error, {bin, code, out}}
    end
  rescue
    e -> {:error, Exception.message(e)}
  end
end
