defmodule MobCi.Build do
  @moduledoc """
  Layer 2: prepare a host app for an activated plugin set and build/install it on
  a booted device via `mix mob.deploy --native --device <serial>` (which builds
  the x86_64 APK, installs it, and pushes the OTP runtime + BEAMs in one step —
  adb push to a redroid over loopback is reliable).

  Host modes:
    * `:harness` — a throwaway app generated by `mix mob.new`, fixtures added as
      path deps + activated. The milestone-1 sample set uses this.
    * `:sloppy_joe` — the real app, activation varied over its own plugins.

  The pure construction (mob.exs / local.properties bodies, deps splice, deploy
  args, aapt permission parsing) is unit-tested; `prepare_harness/2` + `deploy/2`
  shell out (`:integration`). The exact steps below — `--dest` not `--app`, the
  mandatory `mix mob.icon`, the `acknowledge_unsafe_plugins` gate, the OTP cache
  layout — were discovered on the first real device run (2026-06-19).
  """

  alias MobCi.Plugins

  @harness_root Path.expand("../../fixtures/_harness", __DIR__)
  @sdk_dir "/home/kevin/Android/Sdk"

  @type host :: :harness | :sloppy_joe

  # ── pure construction (unit-tested) ──────────────────────────────────────────

  @doc "Manifest-bearing plugins in `set` (tier-0 contributes nothing → omitted)."
  @spec activated_names([atom()]) :: [atom()]
  def activated_names(set), do: for(name <- set, is_map(Plugins.load_manifest(name)), do: name)

  @doc "The harness `mob.exs` body: mob_dir, the activated set, and the unsigned-plugin gate."
  @spec mob_exs([atom()]) :: String.t()
  def mob_exs(set) do
    activated = activated_names(set)

    """
    import Config

    config :mob_dev,
      mob_dir: Path.join(File.cwd!(), "deps/mob"),
      elixir_lib:
        System.get_env("MOB_ELIXIR_LIB", :code.lib_dir(:elixir) |> to_string() |> Path.dirname())

    config :mob, :plugins, #{inspect(activated)}

    # The fixtures are unsigned local prototypes — acknowledge them past the trust gate.
    config :mob, :acknowledge_unsafe_plugins, #{inspect(activated)}
    """
  end

  @doc "The `defp deps do … end` block wiring mob/mob_dev + the activated fixtures as path deps."
  @spec deps_block([atom()], Path.t()) :: String.t()
  def deps_block(set, harness_dir) do
    fixture_deps =
      for name <- activated_names(set) do
        rel = Path.relative_to(Plugins.fixture_dir(name), harness_dir)
        "      {:#{name}, path: \"#{rel}\"}"
      end

    palette =
      if :mob_ci_palette in set,
        do: ["      {:mob_ci_palette, path: \"#{Path.relative_to(Plugins.fixture_dir(:mob_ci_palette), harness_dir)}\"}"],
        else: []

    lines =
      [
        "      {:mob,     \"~> 0.7\"}",
        "      {:mob_dev, \"~> 0.6\", only: :dev, runtime: false}",
        "      {:ecto_sqlite3, \"~> 0.18\"}"
      ] ++ palette ++ fixture_deps

    "  defp deps do\n    [\n" <> Enum.join(lines, ",\n") <> "\n    ]\n  end"
  end

  @doc "Android `local.properties` body (sdk + OTP cache paths + mob_dir)."
  @spec local_properties(Path.t()) :: String.t()
  def local_properties(harness_dir) do
    %{base: base, arm32: arm32, x86_64: x86} = otp_paths()

    """
    sdk.dir=#{@sdk_dir}
    mob.otp_release=#{base}
    mob.otp_release_arm32=#{arm32}
    mob.otp_release_x86_64=#{x86}
    mob.mob_dir=#{Path.join(harness_dir, "deps/mob")}
    """
  end

  @doc "The Android package mob.new derives for an app: `com.example.<app>`."
  @spec package_name(atom() | String.t()) :: String.t()
  def package_name(app), do: "com.example.#{app}"

  @doc "The generated showcase screen module for P5: `<AppModule>.CiShowcase`."
  @spec showcase_module(atom()) :: module()
  def showcase_module(app), do: Module.concat([Macro.camelize(to_string(app)), CiShowcase])

  @doc "Activated plugins that contribute a UI component, with their widget module + id (P5)."
  @spec component_widgets([atom()]) :: [{module(), atom()}]
  def component_widgets(set) do
    for name <- activated_names(set),
        m = Plugins.load_manifest(name),
        comps = Map.get(m, :ui_components, []),
        comps != [],
        comp = hd(comps),
        atom = comp[:atom] do
      {Module.concat([Macro.camelize(to_string(name))]), atom}
    end
  end

  @doc """
  Source for a screen embedding every activated component's widget — what P5
  pushes to confirm components render without a dispatch crash. With no
  components the screen is a plain label (P5 then skips on an empty set).
  """
  @spec showcase_source([atom()], atom()) :: String.t()
  def showcase_source(set, app) do
    widgets =
      case component_widgets(set) do
        [] -> ~s(      <Text text="no components" text_color={:on_surface} />)
        ws -> Enum.map_join(ws, "\n", fn {mod, id} -> "      {#{inspect(mod)}.widget(id: :#{id})}" end)
      end

    """
    defmodule #{inspect(showcase_module(app))} do
      @moduledoc "Generated by mob_ci — embeds every activated UI component for P5."
      use Mob.Screen

      def mount(_params, _session, socket), do: {:ok, socket}

      def render(_assigns) do
        ~MOB\"""
        <Scroll background={:background}>
          <Column background={:background} padding={:space_lg}>
    #{widgets}
          </Column>
        </Scroll>
        \"""
      end
    end
    """
  end

  @doc "A deterministic harness app name for a set (stable → reuses the build cache)."
  @spec harness_app_name([atom()]) :: atom()
  def harness_app_name(set) do
    if Enum.sort(set) == Enum.sort(Plugins.sample_set()),
      do: :mob_ci_harness,
      else: :"mob_ci_h_#{:erlang.phash2(Enum.sort(set))}"
  end

  @doc "Args for the native x86_64 deploy to a specific device serial."
  @spec deploy_args(String.t()) :: [String.t()]
  def deploy_args(serial), do: ["mob.deploy", "--native", "--device", serial]

  @doc "Parse `aapt dump permissions <apk>` into the declared permission set (P6 actual side)."
  @spec parse_permissions(String.t()) :: MapSet.t(String.t())
  def parse_permissions(aapt_output) do
    ~r/uses-permission: name='([^']+)'/
    |> Regex.scan(aapt_output, capture: :all_but_first)
    |> Enum.map(fn [p] -> p end)
    |> MapSet.new()
  end

  # Resolve the OTP cache triple (base/arm32/x86_64) from a single discovered hash.
  defp otp_paths do
    cache = Path.expand("~/.mob/cache")

    hash =
      case Path.wildcard(Path.join(cache, "otp-android-x86_64-*")) do
        [dir | _] -> dir |> Path.basename() |> String.replace_prefix("otp-android-x86_64-", "")
        [] -> nil
      end

    %{
      base: Path.join(cache, "otp-android-#{hash}"),
      arm32: Path.join(cache, "otp-android-arm32-#{hash}"),
      x86_64: Path.join(cache, "otp-android-x86_64-#{hash}")
    }
  end

  # ── exec (integration) ───────────────────────────────────────────────────────

  @doc """
  Prepare the harness for `set`: generate (or reuse) the app, wire fixtures, write
  mob.exs + local.properties, fetch deps, and generate icons. Returns
  `{:ok, %{dir, app, pkg}}`. `reuse: true` (default) keeps an existing prepared
  dir to preserve the gradle/_build cache; `fresh: true` regenerates from scratch.
  """
  @spec prepare_harness([atom()], keyword()) ::
          {:ok, %{dir: Path.t(), app: atom(), pkg: String.t()}} | {:error, term()}
  def prepare_harness(set, opts \\ []) do
    app = harness_app_name(set)
    dir = Path.join(@harness_root, to_string(app))
    pkg = package_name(app)
    reuse = Keyword.get(opts, :reuse, true) and not Keyword.get(opts, :fresh, false)

    result =
      if reuse and File.exists?(Path.join(dir, "mob.exs")) do
        {:ok, %{dir: dir, app: app, pkg: pkg}}
      else
        generate_harness(set, dir, app, pkg)
      end

    # Always (re)write the P5 showcase screen — cheap, and keeps it in sync with
    # the activated set even when the harness dir is reused.
    with {:ok, %{dir: d}} <- result do
      File.mkdir_p!(Path.join(d, "lib/#{app}"))
      File.write!(Path.join(d, "lib/#{app}/ci_showcase.ex"), showcase_source(set, app))
    end

    result
  end

  defp generate_harness(set, dir, app, pkg) do
    File.rm_rf!(dir)
    File.mkdir_p!(@harness_root)

    with {_o, 0} <- sh(["mob.new", to_string(app), "--dest", @harness_root, "--android"], @harness_root),
         :ok <- splice_deps(dir, set),
         :ok <- File.write(Path.join(dir, "mob.exs"), mob_exs(set)),
         :ok <- File.write(Path.join(dir, "android/local.properties"), local_properties(dir)),
         {_o2, 0} <- sh(["deps.get"], dir),
         {_o3, 0} <- sh(["mob.icon"], dir) do
      {:ok, %{dir: dir, app: app, pkg: pkg}}
    else
      {out, code} when is_integer(code) -> {:error, {:harness_prep, code, String.slice(out, -600, 600)}}
      {:error, _} = err -> err
    end
  end

  @doc """
  Prepare ONE harness depending on the whole `pool` (default the device pool), for
  the sweep: activation is then varied per subset via `activate/2` while the
  gradle/zig cache is shared, so each subset rebuilds in ~minutes not ~10min.
  """
  @spec prepare_sweep_harness(keyword()) ::
          {:ok, %{dir: Path.t(), app: atom(), pkg: String.t()}} | {:error, term()}
  def prepare_sweep_harness(opts \\ []) do
    pool = Keyword.get(opts, :pool, MobCi.Sweep.device_pool())
    app = :mob_ci_sweep
    dir = Path.join(@harness_root, to_string(app))
    pkg = package_name(app)
    reuse = Keyword.get(opts, :reuse, true) and not Keyword.get(opts, :fresh, false)

    result =
      if reuse and File.exists?(Path.join(dir, "mob.exs")) do
        {:ok, %{dir: dir, app: app, pkg: pkg}}
      else
        generate_sweep_harness(dir, app, pkg, pool)
      end

    # Always (re)write local.properties — it's machine-specific config mob.new
    # ships as placeholders, and the reuse path would otherwise keep stale paths.
    with {:ok, %{dir: d}} <- result do
      File.write!(Path.join(d, "android/local.properties"), local_properties(d))
    end

    result
  end

  defp generate_sweep_harness(dir, app, pkg, pool) do
    File.rm_rf!(dir)
    File.mkdir_p!(@harness_root)

    with {_o, 0} <- sh(["mob.new", to_string(app), "--dest", @harness_root, "--android"], @harness_root),
         :ok <- File.write(Path.join(dir, "mix.exs"), patch_deps_for(dir, pool)),
         :ok <- activate(dir, pool, app),
         {_o2, 0} <- sh(["deps.get"], dir),
         {_o3, 0} <- sh(["mob.icon"], dir) do
      {:ok, %{dir: dir, app: app, pkg: pkg}}
    else
      {out, code} when is_integer(code) -> {:error, {:sweep_harness_prep, code, String.slice(out, -600, 600)}}
      {:error, _} = err -> err
    end
  end

  defp patch_deps_for(dir, pool) do
    {:ok, body} = File.read(Path.join(dir, "mix.exs"))
    Regex.replace(~r/  defp deps do\n.*?\n  end/s, body, deps_block(pool, dir), global: false)
  end

  @doc "Set the activated subset on a prepared (sweep) harness: rewrite mob.exs + the showcase."
  @spec activate(Path.t(), [atom()], atom()) :: :ok
  def activate(dir, subset, app \\ :mob_ci_sweep) do
    File.write!(Path.join(dir, "mob.exs"), mob_exs(subset))
    File.mkdir_p!(Path.join(dir, "lib/#{app}"))
    File.write!(Path.join(dir, "lib/#{app}/ci_showcase.ex"), showcase_source(subset, app))
    :ok
  end

  # Replace the generated `defp deps do … end` (default showcase plugins) with ours.
  defp splice_deps(dir, set) do
    mix_exs = Path.join(dir, "mix.exs")

    case File.read(mix_exs) do
      {:ok, body} ->
        patched = Regex.replace(~r/  defp deps do\n.*?\n  end/s, body, deps_block(set, dir), global: false)
        File.write(mix_exs, patched)

      err ->
        err
    end
  end

  @doc """
  Build + install + push to `serial` via `mix mob.deploy --native --device`.
  Returns `:ok`, `{:conflict, msgs}` (cross-plugin rejection at validate → P1's
  expected path), or `{:error, reason}`.
  """
  @spec deploy(Path.t(), String.t()) :: :ok | {:conflict, [String.t()]} | {:error, term()}
  def deploy(dir, serial) do
    case sh(deploy_args(serial), dir) do
      {_out, 0} -> :ok
      {out, _code} -> classify_failure(out)
    end
  end

  defp classify_failure(out) do
    if out =~ "declare the same" or out =~ "capability check failed" do
      {:conflict, conflict_lines(out)}
    else
      {:error, {:native_build, String.slice(out, -800, 800)}}
    end
  end

  defp conflict_lines(out) do
    out
    |> String.split("\n")
    |> Enum.filter(&(&1 =~ "declare the same" or &1 =~ "capability"))
    |> Enum.map(&String.trim/1)
  end

  @doc "Locate the harness's built debug APK (for P6 permission reading)."
  @spec locate_apk(Path.t()) :: {:ok, Path.t()} | {:error, :apk_not_found}
  def locate_apk(dir) do
    case Path.wildcard(Path.join(dir, "android/app/build/outputs/apk/**/*.apk")) do
      [apk | _] -> {:ok, apk}
      [] -> {:error, :apk_not_found}
    end
  end

  @doc "Read an APK's declared permissions via aapt (P6 actual side)."
  @spec read_permissions(Path.t()) :: {:ok, MapSet.t(String.t())} | {:error, term()}
  def read_permissions(apk) do
    case aapt(["dump", "permissions", apk]) do
      {:ok, out} -> {:ok, parse_permissions(out)}
      {:error, _} = err -> err
    end
  end

  defp aapt(args) do
    bin =
      System.find_executable("aapt") ||
        (Path.wildcard(Path.join(@sdk_dir, "build-tools/*/aapt")) |> Enum.sort() |> List.last())

    if is_nil(bin), do: {:error, :aapt_not_found}, else: run(bin, args)
  end

  defp sh(args, cd), do: System.cmd("mix", args, cd: cd, stderr_to_stdout: true, env: [{"MIX_ENV", "dev"}])

  defp run(bin, args) do
    case System.cmd(bin, args, stderr_to_stdout: true) do
      {out, 0} -> {:ok, out}
      {out, code} -> {:error, {bin, code, out}}
    end
  rescue
    e -> {:error, Exception.message(e)}
  end
end
