defmodule MobCi.Build do
  @moduledoc """
  Layer 2: turn an activated plugin set into an installable x86_64 APK + the OTP
  tree to inject, by driving `mix mob.deploy --native` on a host project.

  Two host modes (see the design record):

    * `:harness` — a throwaway app generated by `mix mob.new`, with the fixture
      plugins added as path deps and activated. Fast, isolates plugin behavior;
      the milestone-1 fixed sample set uses this (the fixtures need a host that
      depends on them).
    * `:sloppy_joe` — the real app at `~/code/sloppy_joe`, with `config :mob,
      :plugins` varied over its *own* shipped plugins. The realism gate.

  The pure construction (mob.exs body, deploy args, aapt permission parsing —
  P6's actual side) is unit-tested. `prepare/2` + `build/2` shell out and are
  `:integration`; the OTP-tree/APK output locations are confirmed on the first
  real farm run (marked below).
  """

  alias MobCi.Plugins

  @type host :: :harness | :sloppy_joe
  @type artifact :: %{
          status: MobCi.Context.build_status(),
          apk: Path.t() | nil,
          otp_dir: Path.t() | nil,
          permissions: MapSet.t(String.t()) | nil,
          app: atom()
        }

  @doc """
  The `mob.exs` body activating `set` (only manifest-bearing plugins — tier-0
  contributes nothing and is omitted from the activation list).

      config :mob, :plugins, [:mob_ci_haptic, :mob_ci_notes, ...]
  """
  @spec plugins_config([atom()]) :: String.t()
  def plugins_config(set) do
    activated =
      for name <- set, is_map(Plugins.load_manifest(name)), do: name

    "import Config\n\nconfig :mob, :plugins, #{inspect(activated)}\n"
  end

  @doc """
  Path-dep entries for a generated harness's `mix.exs`, one per manifest-bearing
  fixture in `set`. `from_dir` is the harness dir; deps point back at `fixtures/`.
  """
  @spec harness_deps(([atom()]), Path.t()) :: [String.t()]
  def harness_deps(set, from_dir) do
    for name <- set, is_map(Plugins.load_manifest(name)) do
      rel = Path.relative_to(Plugins.fixture_dir(name), from_dir)
      ~s({:#{name}, path: "#{rel}"})
    end
  end

  @doc "Args for the native deploy of an x86_64 build to install on the farm."
  @spec deploy_args(keyword()) :: [String.t()]
  def deploy_args(opts \\ []) do
    base = ["mob.deploy", "--native"]
    if Keyword.get(opts, :x86_64, true), do: base ++ ["--abi", "x86_64"], else: base
  end

  @doc """
  Parse `aapt dump permissions <apk>` output into the set of declared
  permissions — the actual side of P6.

      uses-permission: name='android.permission.CAMERA'
  """
  @spec parse_permissions(String.t()) :: MapSet.t(String.t())
  def parse_permissions(aapt_output) do
    ~r/uses-permission: name='([^']+)'/
    |> Regex.scan(aapt_output, capture: :all_but_first)
    |> Enum.map(fn [p] -> p end)
    |> MapSet.new()
  end

  @doc "Read an APK's declared permissions via aapt (P6 actual side)."
  @spec read_permissions(Path.t()) :: {:ok, MapSet.t(String.t())} | {:error, term()}
  def read_permissions(apk) do
    case aapt(["dump", "permissions", apk]) do
      {:ok, out} -> {:ok, parse_permissions(out)}
      {:error, _} = err -> err
    end
  end

  # Resolve aapt from PATH or the Android SDK build-tools (newest).
  defp aapt(args) do
    bin =
      System.find_executable("aapt") || System.find_executable("aapt2") ||
        (Path.wildcard(Path.expand("~/Android/Sdk/build-tools/*/aapt")) |> Enum.sort() |> List.last())

    cond do
      is_nil(bin) -> {:error, :aapt_not_found}
      true -> run(bin, args)
    end
  end

  defp run(bin, args) do
    case System.cmd(bin, args, stderr_to_stdout: true) do
      {out, 0} -> {:ok, out}
      {out, code} -> {:error, {bin, code, out}}
    end
  rescue
    e -> {:error, Exception.message(e)}
  end

  # ── exec half (integration; output locations confirmed on first farm run) ────

  @harness_root Path.expand("../../fixtures/_harness", __DIR__)

  @doc """
  Generate a throwaway harness app under `fixtures/_harness/<name>` (gitignored),
  add the activated fixtures as path deps, and write `mob.exs` activating them.
  Returns `{:ok, %{dir, app}}`. Idempotent: regenerates a clean dir each call.
  """
  @spec prepare_harness([atom()], keyword()) :: {:ok, %{dir: Path.t(), app: atom()}} | {:error, term()}
  def prepare_harness(set, opts \\ []) do
    app = Keyword.get(opts, :app, harness_app_name(set))
    dir = Path.join(@harness_root, to_string(app))
    File.rm_rf!(dir)
    File.mkdir_p!(Path.dirname(dir))

    with {_out, 0} <- System.cmd("mix", ["mob.new", dir, "--app", to_string(app)], stderr_to_stdout: true),
         :ok <- inject_fixture_deps(dir, set),
         :ok <- File.write(Path.join(dir, "mob.exs"), plugins_config(set)) do
      {:ok, %{dir: dir, app: app}}
    else
      {out, code} when is_integer(code) -> {:error, {:mob_new_failed, code, out}}
      {:error, _} = err -> err
    end
  end

  # A deterministic harness name from the set, so reruns reuse the dir/build cache.
  defp harness_app_name(set) do
    digest = set |> Enum.sort() |> Enum.map_join("_", &(&1 |> to_string() |> String.replace("mob_ci_", "")))
    :"mob_ci_h_#{digest}"
  end

  # Append the fixture path-deps into the generated mix.exs deps/0 list. The exact
  # splice point depends on mob_new's template — confirmed on the first run; this
  # inserts before the closing `]` of the deps list.
  defp inject_fixture_deps(dir, set) do
    mix_exs = Path.join(dir, "mix.exs")
    deps = harness_deps(set, dir)

    case File.read(mix_exs) do
      {:ok, body} ->
        snippet = Enum.map_join(deps, ",\n      ", & &1)
        # naive but deterministic: add to the deps list by appending after `deps do [`
        patched = String.replace(body, ~r/defp deps do\s*\[/, "defp deps do\n    [\n      #{snippet},", global: false)
        File.write(mix_exs, patched)

      err ->
        err
    end
  end

  @doc """
  Full build: prepare the host, fetch deps, native x86_64 deploy, locate the APK +
  OTP tree, and read merged permissions. Returns an artifact map for the Context.
  On a cross-plugin conflict the native build fails at validate; this surfaces as
  `status: {:conflict, msgs}` (P1's expected rejection path).
  """
  @spec build([atom()], keyword()) :: artifact()
  def build(set, opts \\ []) do
    host = Keyword.get(opts, :host, :harness)

    with {:ok, %{dir: dir, app: app}} <- host_dir(host, set, opts),
         {_o, 0} <- System.cmd("mix", ["deps.get"], cd: dir, stderr_to_stdout: true),
         {:ok, apk, otp} <- native_deploy(dir) do
      perms =
        case read_permissions(apk) do
          {:ok, p} -> p
          {:error, _} -> nil
        end

      %{status: :ok, apk: apk, otp_dir: otp, permissions: perms, app: app}
    else
      {:conflict, msgs, app} -> %{status: {:conflict, msgs}, apk: nil, otp_dir: nil, permissions: nil, app: app}
      {:error, reason} -> %{status: {:error, reason}, apk: nil, otp_dir: nil, permissions: nil, app: app_for(host, set)}
      {out, code} when is_integer(code) -> %{status: {:error, {:deps_get, code, out}}, apk: nil, otp_dir: nil, permissions: nil, app: app_for(host, set)}
    end
  end

  defp host_dir(:harness, set, opts), do: prepare_harness(set, opts)

  defp host_dir(:sloppy_joe, set, _opts) do
    dir = Path.expand("~/code/sloppy_joe")
    File.write!(Path.join(dir, "mob.exs"), plugins_config(set))
    {:ok, %{dir: dir, app: :sloppy_joe}}
  end

  defp app_for(:sloppy_joe, _set), do: :sloppy_joe
  defp app_for(:harness, set), do: harness_app_name(set)

  # Run the native deploy, classify a cross-plugin conflict vs a real build error,
  # and locate outputs. The APK + OTP-tree paths under _build / ~/.mob are
  # confirmed against real `mix mob.deploy --native` output on the first farm run.
  defp native_deploy(dir) do
    case System.cmd("mix", deploy_args(), cd: dir, stderr_to_stdout: true) do
      {_out, 0} -> locate_outputs(dir)
      {out, _code} -> classify_build_failure(out)
    end
  end

  defp classify_build_failure(out) do
    if out =~ "plugin" and (out =~ "declare the same" or out =~ "conflict" or out =~ "capability check failed") do
      {:conflict, conflict_lines(out), nil}
    else
      {:error, {:native_build, String.slice(out, -800, 800)}}
    end
  end

  defp conflict_lines(out) do
    out
    |> String.split("\n")
    |> Enum.filter(&(&1 =~ "declare the same" or &1 =~ "capability"))
    |> Enum.map(&String.trim/1)
  end

  defp locate_outputs(dir) do
    apk =
      Path.wildcard(Path.join(dir, "android/**/outputs/**/*-x86_64-*.apk")) ++
        Path.wildcard(Path.join(dir, "android/**/outputs/**/*.apk"))

    otp =
      Path.wildcard(Path.expand("~/.mob/cache/otp-android-x86_64-*")) ++
        Path.wildcard(Path.join(dir, "_build/**/otp"))

    case {List.first(apk), List.first(otp)} do
      {nil, _} -> {:error, {:apk_not_found, dir}}
      {_, nil} -> {:error, {:otp_tree_not_found, dir}}
      {a, o} -> {:ok, a, o}
    end
  end
end
