defmodule MobCi.Host do
  @moduledoc """
  A host app for one (set, version row): generated by the row's own mob_new
  (`mix mob.new <app> --blank`, `--local` on a git row, so the generator is
  under test every night), then rewritten to pin exactly what `MobCi.Versions`
  resolved:

    * `mix.exs` deps — mob, mob_dev, ecto_sqlite3 and the activated plugins as
      `== version` Hex deps or `path:` deps on the cached checkouts;
    * `mob.exs` — `config :mob, :plugins` (the set), `:trusted_plugins` (every
      first-party plugin on the shared release key, as mob_new's template
      pre-trusts them) and `:acknowledge_unsafe_plugins` (the plugins whose
      dep directory ships no signature: path checkouts and unsigned releases,
      as mob_new's `--local` does).

  Failures carry the layer they belong to: anything the generator does is
  `:mob_new`; `mix deps.get` and `mix compile` are `:elixir`. The APK build
  (`mix mob.deploy`) is `MobCi.Build.deploy/2`'s job, unchanged. Hosts live
  under `fixtures/_hosts/<app>` (gitignored) and are reused across runs so the
  build cache survives; `fresh: true` regenerates.

  The pure parts (`app_name/2`, `deps_block/2`, `mob_exs/3`, `trust/2`) are
  unit-tested; `generate/4` shells out (`:integration`).
  """

  alias MobCi.{Sets, Versions}

  @hosts_root Path.expand("../../fixtures/_hosts", __DIR__)

  # The shared mob release key's fingerprint, as `mix mob.new` writes it into
  # every generated mob.exs (priv/templates/mob.new/mob.exs.eex).
  @first_party_key "ed25519:nc56w+1Kx0gIt/4EkHxnMZCKHMzp4+S5kS/HoSzEZkg="

  @type layer :: :mob_new | :elixir
  @type host :: %{dir: Path.t(), app: atom(), pkg: String.t(), set: String.t(), versions: map()}

  @doc "The shared release key fingerprint mob_new pre-trusts."
  def first_party_key, do: @first_party_key

  @doc "Where generated hosts live."
  def hosts_root, do: @hosts_root

  # ── pure ─────────────────────────────────────────────────────────────────────

  @doc """
  A deterministic, `mix mob.new`-valid app name for a (set, row):
  `ci_<set>_<row>` with every non-alphanumeric run folded to `_`, so the same
  cell always lands in the same directory (build-cache reuse).
  """
  @spec app_name(String.t(), Versions.row()) :: atom()
  def app_name(set_name, row) do
    "ci_#{set_name}_#{Versions.row_to_string(row)}"
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9]+/, "_")
    |> String.trim_trailing("_")
    |> String.to_atom()
  end

  @doc "The `defp deps do … end` block: core deps, ecto, then the plugin deps, in that order."
  @spec deps_block([Versions.dep()], [Versions.dep()]) :: String.t()
  def deps_block(core_deps, plugin_deps) do
    lines =
      Enum.map(
        core_deps ++ [{:ecto_sqlite3, "~> 0.18"}] ++ plugin_deps,
        &("      " <> Versions.render_dep(&1))
      )

    "  defp deps do\n    [\n" <> Enum.join(lines, ",\n") <> "\n    ]\n  end"
  end

  @doc """
  The host `mob.exs`: mob_dir at the dep (works for Hex and path deps alike,
  since Mix materialises both under `deps/`), the activated set, the trust map
  and the acknowledgement list.
  """
  @spec mob_exs([atom()], %{atom() => String.t()}, [atom()]) :: String.t()
  def mob_exs(plugins, trusted, acknowledged) do
    """
    # Generated by mob_ci (MobCi.Host) — the activation for one CI cell.
    import Config

    config :mob_dev,
      mob_dir: Path.join(File.cwd!(), "deps/mob"),
      elixir_lib:
        System.get_env("MOB_ELIXIR_LIB", :code.lib_dir(:elixir) |> to_string() |> Path.dirname())

    config :mob, :plugins, #{inspect(plugins, limit: :infinity)}

    # First-party plugins are signed in release CI with the shared mob key;
    # this is its fingerprint, as `mix mob.new` pre-trusts it.
    config :mob, :trusted_plugins, #{inspect(trusted, limit: :infinity)}

    # Path checkouts (git rows) and unsigned releases ship no signature; the
    # trust gate needs this acknowledgement to build them.
    config :mob, :acknowledge_unsafe_plugins, #{inspect(acknowledged, limit: :infinity)}
    """
  end

  @doc """
  `{trusted, acknowledged}` for `plugins` given the host's `deps/` dir: every
  plugin is trusted on the first-party key; a plugin whose dep ships no
  `priv/mob_plugin.sig` is acknowledged as unsigned.
  """
  @spec trust([atom()], Path.t()) :: {%{atom() => String.t()}, [atom()]}
  def trust(plugins, deps_dir) do
    trusted = Map.new(plugins, &{&1, @first_party_key})

    unsigned =
      Enum.reject(
        plugins,
        &File.regular?(Path.join([deps_dir, to_string(&1), "priv", "mob_plugin.sig"]))
      )

    {trusted, unsigned}
  end

  @doc "Swap the generated `defp deps do … end` for ours."
  @spec splice_deps(String.t(), String.t()) :: String.t()
  def splice_deps(mix_exs, block),
    do: Regex.replace(~r/  defp deps do\n.*?\n  end/s, mix_exs, block, global: false)

  @doc """
  `mix mob.new` argv for a host: blank, Android only, deps fetched by us.
  `--local` only on `master` — mob_new's `--local` needs both mob and mob_dev
  as checkouts; an `rc:` row pins one repo and gets its path dep from the
  `mix.exs` rewrite instead.
  """
  @spec mob_new_args(atom(), Versions.row()) :: [String.t()]
  def mob_new_args(app, row) do
    base = [
      "mob.new",
      to_string(app),
      "--blank",
      "--android",
      "--no-install",
      "--dest",
      @hosts_root
    ]

    if row == :master, do: base ++ ["--local"], else: base
  end

  @doc "Env for the generator (run in prod so only its runtime deps are fetched); `--local` reads MOB_DIR / MOB_DEV_DIR / MOB_NEW_DIR."
  @spec mob_new_env(Versions.resolved()) :: [{String.t(), String.t()}]
  def mob_new_env(%{row: :master, repos: repos}) do
    [
      {"MIX_ENV", "prod"},
      {"MOB_DIR", repos.mob.dir},
      {"MOB_DEV_DIR", repos.mob_dev.dir},
      {"MOB_NEW_DIR", repos.mob_new.dir}
    ]
  end

  def mob_new_env(_resolved), do: [{"MIX_ENV", "prod"}]

  # ── exec (integration) ───────────────────────────────────────────────────────

  @doc """
  Generate (or reuse) the host for `set_spec` under `resolved`, pin its deps,
  fetch and compile them. Returns the host or `{:error, {layer, reason}}`.
  Options: `fresh: true` regenerates; `compile: false` stops after `deps.get`.
  """
  @spec generate(Sets.spec(), [atom()], Versions.resolved(), keyword()) ::
          {:ok, host()} | {:error, {layer(), term()}}
  def generate(set_spec, plugins, %{row: row} = resolved, opts \\ []) do
    set_name = Sets.name(set_spec)
    app = app_name(set_name, row)
    dir = Path.join(@hosts_root, to_string(app))
    fresh = Keyword.get(opts, :fresh, false)

    host = %{
      dir: dir,
      app: app,
      pkg: "com.example.#{app}",
      set: set_name,
      versions: Versions.record(resolved)
    }

    with :ok <- maybe_generate(dir, app, resolved, fresh),
         :ok <- write_mix_exs(dir, plugins, resolved),
         :ok <- mix(["deps.get"], dir, :elixir),
         :ok <- write(Path.join(dir, "mob.exs"), mob_exs_for(dir, plugins), :elixir),
         :ok <- maybe_compile(dir, Keyword.get(opts, :compile, true)) do
      {:ok, host}
    end
  end

  @doc "Switch a generated host to `subset` (the sweep's per-subset activation): rewrite mob.exs with the trust for that subset."
  @spec activate(host(), [atom()]) :: :ok
  def activate(%{dir: dir}, subset),
    do: File.write!(Path.join(dir, "mob.exs"), mob_exs_for(dir, subset))

  defp maybe_generate(dir, app, resolved, fresh) do
    if not fresh and File.regular?(Path.join(dir, "mix.exs")) do
      :ok
    else
      File.rm_rf!(dir)
      File.mkdir_p!(@hosts_root)
      mob_new_dir = Versions.mob_new_dir(resolved)
      env = mob_new_env(resolved)

      with :ok <- mix(["deps.get"], mob_new_dir, :mob_new, env),
           :ok <- mix(mob_new_args(app, resolved.row), mob_new_dir, :mob_new, env),
           do:
             if(File.regular?(Path.join(dir, "mix.exs")),
               do: :ok,
               else: {:error, {:mob_new, {:no_project, dir}}}
             )
    end
  end

  defp write_mix_exs(dir, plugins, resolved) do
    path = Path.join(dir, "mix.exs")
    block = deps_block(Versions.core_deps(resolved), Versions.plugin_deps(resolved, plugins))

    case File.read(path) do
      {:ok, body} -> write(path, splice_deps(body, block), :mob_new)
      {:error, reason} -> {:error, {:mob_new, {:mix_exs, reason}}}
    end
  end

  defp write(path, body, layer) do
    case File.write(path, body) do
      :ok -> :ok
      {:error, reason} -> {:error, {layer, {:write, path, reason}}}
    end
  end

  defp mob_exs_for(dir, plugins) do
    {trusted, unsigned} = trust(plugins, Path.join(dir, "deps"))
    mob_exs(plugins, trusted, unsigned)
  end

  defp maybe_compile(_dir, false), do: :ok
  defp maybe_compile(dir, true), do: mix(["compile"], dir, :elixir)

  defp mix(args, cd, layer, env \\ [{"MIX_ENV", "dev"}]) do
    case System.cmd("mix", args, cd: cd, env: env, stderr_to_stdout: true) do
      {_out, 0} -> :ok
      {out, code} -> {:error, {layer, {hd(args), code, String.slice(out, -1200, 1200)}}}
    end
  end
end
