defmodule MobCi.Host do
  @moduledoc """
  A host app for one (set, version row): generated by the row's own mob_new
  (`mix mob.new <app> --blank`, `--local` on `master`, so the generator is
  under test every night), then rewritten to pin exactly what `MobCi.Versions`
  resolved:

    * `mix.exs` deps — mob, mob_dev and the activated plugins as `== version`
      Hex deps or `path:` deps on the cached checkouts, keeping whatever else
      the row's mob_new generated (ecto, credo, …);
    * `mob.exs` — `mob_dir` (the Hex dep under `deps/mob`, or the pinned
      checkout on a git row), `config :mob, :plugins` (the set),
      `:trusted_plugins` (every first-party plugin on the shared release key,
      as mob_new's template pre-trusts them) and `:acknowledge_unsafe_plugins`
      (the plugins the row supplies as path checkouts — release CI signs only
      the Hex packages — exactly what mob_new's `--local` acknowledges);
    * `android/local.properties` (sdk + OTP cache + mob_dir) and `mix mob.icon`,
      the prep `mix mob.deploy` needs, as the fixture harness does.

  Failures carry the layer they belong to: anything the generator does is
  `:mob_new`; `mix deps.get`, `mix compile` and `mix mob.icon` are `:elixir`.
  The APK build (`mix mob.deploy`) is `MobCi.Build.deploy/2`'s job, unchanged.
  Hosts live under `fixtures/_hosts/<app>` (gitignored) and are reused across
  runs so the build cache survives, but only while the same mob_new pin
  generated them (`.mob_ci_generator`); a new mob_new sha or release, or
  `fresh: true`, regenerates.

  The pure parts (`app_name/2`, `deps_block/3`, `generated_extras/1`,
  `mob_exs/4`, `mob_dir/2`, `trust/2`) are unit-tested; `generate/4` shells
  out (`:integration`).
  """

  alias MobCi.{Build, Sets, Versions}

  @hosts_root Path.expand("../../fixtures/_hosts", __DIR__)
  @generator_marker ".mob_ci_generator"
  @deps_block ~r/  defp deps do\n.*?\n  end/s

  # The shared mob release key's fingerprint, as `mix mob.new` writes it into
  # every generated mob.exs (priv/templates/mob.new/mob.exs.eex).
  @first_party_key "ed25519:nc56w+1Kx0gIt/4EkHxnMZCKHMzp4+S5kS/HoSzEZkg="

  @type layer :: :mob_new | :elixir
  @type host :: %{dir: Path.t(), app: atom(), pkg: String.t(), set: String.t(), versions: map()}

  @doc "The shared release key fingerprint mob_new pre-trusts."
  def first_party_key, do: @first_party_key

  @doc "Where generated hosts live."
  def hosts_root, do: @hosts_root

  # ── pure ─────────────────────────────────────────────────────────────────────

  @doc """
  A deterministic, `mix mob.new`-valid app name for a (set, row):
  `ci_<set>_<row>` with every non-alphanumeric run folded to `_`, so the same
  cell always lands in the same directory (build-cache reuse).
  """
  @spec app_name(String.t(), Versions.row()) :: atom()
  def app_name(set_name, row) do
    "ci_#{set_name}_#{Versions.row_to_string(row)}"
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9]+/, "_")
    |> String.trim_trailing("_")
    |> String.to_atom()
  end

  @doc """
  The `defp deps do … end` block: the core deps, then the lines the row's
  mob_new generated that aren't mob/mob_dev/plugins (`generated_extras/1`),
  then the plugin deps.
  """
  @spec deps_block([Versions.dep()], [String.t()], [Versions.dep()]) :: String.t()
  def deps_block(core_deps, extras, plugin_deps) do
    lines =
      Enum.map(core_deps, &Versions.render_dep/1) ++
        extras ++ Enum.map(plugin_deps, &Versions.render_dep/1)

    "  defp deps do\n    [\n" <>
      Enum.map_join(lines, ",\n", &("      " <> &1)) <> "\n    ]\n  end"
  end

  @doc """
  The dep entries of a generated `mix.exs` that the row does not pin — every
  `{:name, …}` in its deps block other than mob, mob_dev, mob_new and the
  first-party plugins (ecto_sqlite3, credo, ex_slop today) — as source lines,
  so the host keeps what the row's mob_new chose for them.
  """
  @spec generated_extras(String.t()) :: [String.t()]
  def generated_extras(mix_exs) do
    pinned = [:mob, :mob_dev, :mob_new | Versions.plugins()]

    case Regex.run(~r/  defp deps do\n    \[\n(.*?)\n    \]\n  end/s, mix_exs) do
      [_, body] ->
        body
        |> String.split("\n")
        |> Enum.map(&String.trim/1)
        |> Enum.filter(&String.starts_with?(&1, "{:"))
        |> Enum.map(&String.trim_trailing(&1, ","))
        |> Enum.reject(fn line ->
          case Regex.run(~r/^\{:([a-z0-9_]+)/, line) do
            [_, name] -> String.to_atom(name) in pinned
            nil -> true
          end
        end)

      nil ->
        []
    end
  end

  @doc """
  Where mob_dev finds mob's native sources for this host: the Hex dep under
  `deps/mob`, or the pinned checkout on a git row (a `path:` dep is never
  copied under `deps/`, and mob_dev's MobDirCheck compares `mob_dir` with the
  dep's real path).
  """
  @spec mob_dir(Path.t(), Versions.resolved()) :: Path.t()
  def mob_dir(_host_dir, %{repos: %{mob: %{source: {:git, _}, dir: dir}}}) when is_binary(dir),
    do: dir

  def mob_dir(host_dir, _resolved), do: Path.join(host_dir, "deps/mob")

  @doc """
  The host `mob.exs`: mob_dir, the activated set, the trust map and the
  acknowledgement list. `extra` is appended to the `config :mob_dev` block
  (the iOS lane's `ios_bundle_id` / `ios_team_id`).
  """
  @spec mob_exs(Path.t(), [atom()], %{atom() => String.t()}, [atom()], keyword()) :: String.t()
  def mob_exs(mob_dir, plugins, trusted, acknowledged, extra \\ []) do
    """
    # Generated by mob_ci (MobCi.Host) — the activation for one CI cell.
    import Config

    config :mob_dev,
      mob_dir: #{inspect(mob_dir)},
    #{Enum.map_join(extra, "", fn {k, v} -> "  #{k}: #{inspect(v)},\n" end)}  elixir_lib:
        System.get_env("MOB_ELIXIR_LIB", :code.lib_dir(:elixir) |> to_string() |> Path.dirname())

    config :mob, :plugins, #{inspect(plugins, limit: :infinity)}

    # First-party plugins are signed in release CI with the shared mob key;
    # this is its fingerprint, as `mix mob.new` pre-trusts it.
    config :mob, :trusted_plugins, #{render_map(trusted)}

    # Path checkouts (git rows) carry no release signature; the trust gate
    # needs this acknowledgement to build them, as under `mix mob.new --local`.
    config :mob, :acknowledge_unsafe_plugins, #{inspect(acknowledged, limit: :infinity)}
    """
  end

  # A map literal in sorted key order. `inspect/1` prints small atom-keyed maps
  # in atom-creation order on OTP 26+, which would make the generated file (and
  # its diff between two runs) depend on what the VM had loaded first.
  defp render_map(map) do
    entries = map |> Enum.sort() |> Enum.map_join(", ", fn {k, v} -> "#{k}: #{inspect(v)}" end)
    "%{#{entries}}"
  end

  @doc """
  `{trusted, acknowledged}` for `plugins` under the resolved row: every plugin
  is trusted on the first-party key; the ones the row supplies as git
  checkouts are acknowledged as unsigned. A Hex release is never acknowledged,
  so one that ships without its signature fails the gate here exactly as it
  does for a user.
  """
  @spec trust([atom()], Versions.resolved()) :: {%{atom() => String.t()}, [atom()]}
  def trust(plugins, %{repos: repos}) do
    trusted = Map.new(plugins, &{&1, @first_party_key})
    acknowledged = Enum.filter(plugins, &match?(%{source: {:git, _}}, Map.get(repos, &1)))
    {trusted, acknowledged}
  end

  @doc """
  Swap the generated `defp deps do … end` for ours. A template whose deps
  block this doesn't recognise is an error (layer `mob_new`), not a host
  silently built on mob_new's own `~>` requirements.
  """
  @spec splice_deps(String.t(), String.t()) ::
          {:ok, String.t()} | {:error, {:mob_new, :deps_block_not_found}}
  def splice_deps(mix_exs, block) do
    if Regex.match?(@deps_block, mix_exs),
      do: {:ok, Regex.replace(@deps_block, mix_exs, block, global: false)},
      else: {:error, {:mob_new, :deps_block_not_found}}
  end

  @doc """
  `mix mob.new` argv for a host: blank, one platform (`--android` by default,
  `--ios` for the iOS lane), deps fetched by us, generated under `root`.
  `--local` only on `master` — mob_new's `--local` needs both mob and mob_dev
  as checkouts; an `rc:` row pins one repo and gets its path dep from the
  `mix.exs` rewrite instead.
  """
  @spec mob_new_args(atom(), Versions.row(), :android | :ios, Path.t()) :: [String.t()]
  def mob_new_args(app, row, platform \\ :android, root \\ @hosts_root) do
    base = [
      "mob.new",
      to_string(app),
      "--blank",
      "--#{platform}",
      "--no-install",
      "--dest",
      root
    ]

    if row == :master, do: base ++ ["--local"], else: base
  end

  @doc "Env for the generator (run in prod so only its runtime deps are fetched); `--local` reads MOB_DIR / MOB_DEV_DIR / MOB_NEW_DIR."
  @spec mob_new_env(Versions.resolved()) :: [{String.t(), String.t()}]
  def mob_new_env(%{row: :master, repos: repos}) do
    [
      {"MIX_ENV", "prod"},
      {"MOB_DIR", repos.mob.dir},
      {"MOB_DEV_DIR", repos.mob_dev.dir},
      {"MOB_NEW_DIR", repos.mob_new.dir}
    ]
  end

  def mob_new_env(_resolved), do: [{"MIX_ENV", "prod"}]

  @doc "The reuse key of a host: the mob_new pin that generated it (`version sha`)."
  @spec generator_id(Versions.resolved()) :: String.t()
  def generator_id(%{repos: %{mob_new: pin}}), do: "#{pin.version || "?"} #{pin.sha || "hex"}"

  # ── exec (integration) ───────────────────────────────────────────────────────

  @doc """
  Generate (or reuse) the host for `set_spec` under `resolved`, pin its deps,
  fetch and compile them, write local.properties and the icons. Returns the
  host or `{:error, {layer, reason}}`. Options:

    * `fresh: true` regenerates;
    * `compile: false` stops after `deps.get` (no compile, icons or
      local.properties);
    * `platform: :android | :ios` (default `:android`) is the one platform
      mob_new generates; an iOS host has no `android/local.properties`;
    * `root:` the directory hosts are generated under (default
      `hosts_root/0`; the Mac worker uses a scratch dir it deletes);
    * `mob_exs:` extra `config :mob_dev` entries (`mob_exs/5`).

  A reused host must have been generated by the same mob_new pin for the same
  platform (`.mob_ci_generator`).
  """
  @spec generate(Sets.spec(), [atom()], Versions.resolved(), keyword()) ::
          {:ok, host()} | {:error, {layer(), term()}}
  def generate(set_spec, plugins, %{row: row} = resolved, opts \\ []) do
    set_name = Sets.name(set_spec)
    app = app_name(set_name, row)
    root = Keyword.get(opts, :root, @hosts_root)
    platform = Keyword.get(opts, :platform, :android)
    extra = Keyword.get(opts, :mob_exs, [])
    dir = Path.join(root, to_string(app))
    fresh = Keyword.get(opts, :fresh, false)

    host = %{
      dir: dir,
      app: app,
      pkg: "com.example.#{app}",
      set: set_name,
      versions: Versions.record(resolved)
    }

    with :ok <- maybe_generate(dir, app, resolved, {platform, root}, fresh),
         :ok <- write_mix_exs(dir, plugins, resolved),
         :ok <- mix(["deps.get"], dir, :elixir),
         :ok <-
           write(Path.join(dir, "mob.exs"), mob_exs_for(dir, plugins, resolved, extra), :elixir),
         :ok <- maybe_finish(dir, resolved, platform, Keyword.get(opts, :compile, true)) do
      {:ok, host}
    end
  end

  @doc "Switch a generated host to `subset` (the sweep's per-subset activation): rewrite mob.exs with the trust for that subset."
  @spec activate(host(), [atom()], Versions.resolved()) :: :ok
  def activate(%{dir: dir}, subset, resolved),
    do: File.write!(Path.join(dir, "mob.exs"), mob_exs_for(dir, subset, resolved, []))

  defp maybe_generate(dir, app, resolved, {platform, root}, fresh) do
    marker = Path.join(dir, @generator_marker)
    id = "#{generator_id(resolved)} #{platform}"

    if not fresh and File.regular?(Path.join(dir, "mix.exs")) and File.read(marker) == {:ok, id} do
      :ok
    else
      File.rm_rf!(dir)
      File.mkdir_p!(root)
      mob_new_dir = Versions.mob_new_dir(resolved)
      env = mob_new_env(resolved)

      with :ok <- mix(["deps.get"], mob_new_dir, :mob_new, env),
           :ok <- mix(mob_new_args(app, resolved.row, platform, root), mob_new_dir, :mob_new, env),
           :ok <- generated?(dir) do
        write(marker, id, :mob_new)
      end
    end
  end

  defp generated?(dir),
    do:
      if(File.regular?(Path.join(dir, "mix.exs")),
        do: :ok,
        else: {:error, {:mob_new, {:no_project, dir}}}
      )

  defp write_mix_exs(dir, plugins, resolved) do
    path = Path.join(dir, "mix.exs")

    case File.read(path) do
      {:ok, body} ->
        block =
          deps_block(
            Versions.core_deps(resolved),
            generated_extras(body),
            Versions.plugin_deps(resolved, plugins)
          )

        with {:ok, patched} <- splice_deps(body, block), do: write(path, patched, :mob_new)

      {:error, reason} ->
        {:error, {:mob_new, {:mix_exs, reason}}}
    end
  end

  defp mob_exs_for(dir, plugins, resolved, extra) do
    {trusted, acknowledged} = trust(plugins, resolved)
    mob_exs(mob_dir(dir, resolved), plugins, trusted, acknowledged, extra)
  end

  defp maybe_finish(_dir, _resolved, _platform, false), do: :ok

  defp maybe_finish(dir, _resolved, :ios, true) do
    with :ok <- mix(["compile"], dir, :elixir), do: mix(["mob.icon"], dir, :elixir)
  end

  defp maybe_finish(dir, resolved, :android, true) do
    with :ok <- mix(["compile"], dir, :elixir),
         :ok <-
           write(
             Path.join(dir, "android/local.properties"),
             local_properties(dir, resolved),
             :elixir
           ),
         do: mix(["mob.icon"], dir, :elixir)
  end

  # The harness's local.properties (sdk + OTP cache), with mob.mob_dir pointing
  # where this host's mob really is.
  defp local_properties(dir, resolved) do
    Regex.replace(
      ~r/^mob\.mob_dir=.*$/m,
      Build.local_properties(dir),
      "mob.mob_dir=#{mob_dir(dir, resolved)}"
    )
  end

  defp write(path, body, layer) do
    case File.write(path, body) do
      :ok -> :ok
      {:error, reason} -> {:error, {layer, {:write, path, reason}}}
    end
  end

  defp mix(args, cd, layer, env \\ [{"MIX_ENV", "dev"}]) do
    case System.cmd("mix", args, cd: cd, env: env, stderr_to_stdout: true) do
      {_out, 0} -> :ok
      {out, code} -> {:error, {layer, {hd(args), code, String.slice(out, -1200, 1200)}}}
    end
  end
end
