/* mob_ci_haptic_nif — tier-1 plugin NIF.
 *
 * The compile-time merge engine compiles this with
 * -DSTATIC_ERLANG_NIF -DSTATIC_ERLANG_NIF_LIBNAME=mob_ci_haptic_nif,
 * so ERL_NIF_INIT emits the static init symbol mob_ci_haptic_nif_nif_init()
 * that the driver_tab generated by `mix mob.regen_driver_tab` references.
 */
#include <erl_nif.h>

static ERL_NIF_TERM ping(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
  (void)argc;
  (void)argv;
  return enif_make_atom(env, "ok");
}

static ErlNifFunc nif_funcs[] = {
    {"ping", 0, ping},
};

ERL_NIF_INIT(mob_ci_haptic_nif, nif_funcs, NULL, NULL, NULL, NULL)
