defmodule Mix.Tasks.Ci.Sweep do
  @shortdoc "Property sweep over plugin-activation subsets (static or on-device)"
  @moduledoc """
  The property sweep — generate plugin-activation subsets and check invariants
  across the combination space, shrinking failures to the minimal offending set.

      mix ci.sweep --static            # cheap: cross_validate soundness over the fixture space
      mix ci.sweep --runs 4            # device: 4 sampled subsets through P1–P11 + shrink
      mix ci.sweep --static --set all --versions hex     # minimal conflicting cores of a real set
      mix ci.sweep --runs 4 --set demo --versions master # device sweep on a generated host

  ## Modes

    * `--static` — generate subsets and verify `cross_validate` flags a conflict
      iff the subset actually collides. Milliseconds, no farm. Exit non-zero if
      any inconsistency is found (a validator soundness bug), each minimized.
      With a cell (`--set`/`--versions`) the pool is the set's real plugins at
      the row's versions and there is no collision oracle: the sweep instead
      reports every minimal subset `cross_validate` rejects (the pairs that
      can't be activated together), exit non-zero if there are any.

    * default (device) — run `--runs N` (default 4) sampled subsets of the
      device pool through the full catalog on one reused harness + container, and
      shrink any failing subset to its minimal core. Self-starts distribution (so
      a plain `mix ci.sweep --runs N` works — no `elixir --name` wrapper needed)
      and exits non-zero if any sampled subset fails or errors. Expensive (one
      build per activation switch) — best scheduled in a low-traffic window.
      With a cell the host is generated by the row's mob_new (`MobCi.Host`) with
      the whole set as deps, and every result carries the set name + versions.
  """
  use Mix.Task

  alias MobCi.{Build, Cell, Dist, Result, Store, Sweep, Versions}

  @switches [
    static: :boolean,
    runs: :integer,
    count: :integer,
    set: :string,
    versions: :string,
    fresh: :boolean,
    store: :string
  ]

  @impl Mix.Task
  def run(argv) do
    {opts, _, _} = OptionParser.parse(argv, switches: @switches)
    static? = opts[:static] == true or is_nil(opts[:runs])

    # The static sweep keeps the plugins parked in priv/sets/exclusions.exs in
    # the pool (the collision that parked them must stay visible); device
    # sweeps build hosts, so they leave them out.
    cell = if opts[:set] || opts[:versions], do: Cell.plan!(opts[:set], opts[:versions], include_excluded: static?)
    if cell, do: Mix.shell().info(Cell.describe(cell))

    cond do
      cell && opts[:static] -> static_cell(cell, opts)
      cell && is_nil(opts[:runs]) -> static_cell(cell, opts)
      opts[:static] == true or is_nil(opts[:runs]) -> static(opts)
      cell -> device([cell: cell, runs: opts[:runs], fresh: opts[:fresh] == true], cell, opts)
      true -> device([runs: opts[:runs]], nil, opts)
    end
  end

  defp device(sweep_opts, cell, opts) do
    Dist.ensure!()

    case Sweep.device_sweep(sweep_opts) do
      {:error, reason} ->
        Mix.shell().error("device sweep could not start: #{inspect(reason)}")
        exit({:shutdown, 2})

      %{ran: ran} = summary ->
        Mix.shell().info("\n" <> Sweep.summarize(summary))
        record_device(ran, cell, opts)
        failed = Enum.count(ran, fn {_subset, {v, _}} -> v in [:fail, :error] end)

        if failed > 0 do
          Mix.shell().error("device sweep: #{failed}/#{length(ran)} sampled subset(s) failed.")
          exit({:shutdown, 1})
        else
          Mix.shell().info("device sweep: all #{length(ran)} sampled subset(s) green.")
        end
    end
  end

  defp static(opts) do
    findings = Sweep.static_findings(count: Keyword.get(opts, :count, 300))

    result =
      if findings == [],
        do: Result.pass(:sweep_static, "cross_validate sound over the sampled fixture subsets"),
        else:
          Result.fail(:sweep_static, "cross_validate inconsistencies", "#{length(findings)} minimal inconsistency(ies)", findings)
          |> Result.at(:static)

    record_static(opts, "sweep:fixtures", "harness", nil, result)

    if findings == [] do
      Mix.shell().info("✓ static sweep: cross_validate is sound over the sampled subset space.")
    else
      Mix.shell().error("✗ static sweep found #{length(findings)} inconsistency(ies):")

      for f <- findings do
        Mix.shell().error(
          "  minimal #{inspect(f.minimal)} — cross_validate=#{f.cross_validate}, colliding=#{f.colliding}"
        )
      end

      exit({:shutdown, 1})
    end
  end

  defp static_cell(cell, opts) do
    cores = Sweep.static_conflicts(pool: cell.plugins, count: Keyword.get(opts, :count, 300))

    result =
      if cores == [],
        do: Result.pass(:sweep_static, "every sampled subset composes (cross_validate)"),
        else:
          Result.fail(:sweep_static, "minimal conflicting cores", Enum.map_join(cores, "; ", &inspect/1), cores)
          |> Result.at(:static)

    record_static(opts, "sweep:#{cell.set}", row(cell), Versions.record(cell.resolved), result)

    if cores == [] do
      Mix.shell().info(
        "✓ static sweep: every sampled subset of #{cell.set} composes (cross_validate)."
      )
    else
      Mix.shell().error(
        "✗ static sweep: #{length(cores)} minimal conflicting core(s) in #{cell.set}:"
      )

      for core <- cores, do: Mix.shell().error("  #{inspect(core)}")
      exit({:shutdown, 1})
    end
  end

  # ── the results store ───────────────────────────────────────────────────────

  defp row(nil), do: "harness"
  defp row(cell), do: Versions.row_to_string(cell.row)

  defp open_run(opts, versions_row) do
    store = Store.open!(opts[:store] || Store.default_path())
    {:ok, run_id} = Store.record_run(store, %{trigger: "ci.sweep", versions_row: versions_row})
    {store, run_id}
  end

  defp record_static(opts, set, versions_row, versions, result) do
    {store, run_id} = open_run(opts, versions_row)
    verdict = if result.status == :pass, do: :ok, else: :fail
    meta = %{set: set, platform: :all, path: "static", versions: versions, duration_ms: nil, log_path: nil}
    Store.record_results(store, run_id, meta, {verdict, [result]})
    Store.close(store)
  end

  # Every sampled subset is a cell `sweep:<plugins>` on the deploy path.
  defp record_device(ran, cell, opts) do
    {store, run_id} = open_run(opts, row(cell))
    versions = if cell, do: Versions.record(cell.resolved)

    for {subset, outcome} <- ran do
      meta = %{
        set: "sweep:" <> Enum.join(subset, ","),
        platform: :android,
        path: Build.path_label(:deploy),
        versions: versions,
        duration_ms: nil,
        log_path: nil
      }

      Store.record_results(store, run_id, meta, stored_outcome(outcome))
    end

    Mix.shell().info("recorded #{length(ran)} sweep cell(s) in #{store.path}")
    Store.close(store)
  end

  @doc false
  # A device-sweep subset outcome as `MobCi.Store.record_results/4` takes it.
  # A subset that never reached the catalog failed to launch (boot), to
  # build (deploy path, with mob_dev's named plugin when there is one), or to
  # get the row's static verdict (the validator project: Elixir).
  def stored_outcome({:pass, results}), do: {:ok, results}
  def stored_outcome({verdict, results}) when verdict in [:fail, :error] and is_list(results), do: {:fail, results}

  def stored_outcome({:error, reason}) do
    layer =
      case reason do
        {:node_never_registered, _} -> :boot
        {:launch_failed, _, _} -> :boot
        {:row_validator, _} -> :elixir
        other -> Build.path_failure_layer(:deploy, other)
      end

    {:error, reason, layer}
  end
end
