defmodule Mix.Tasks.Ci.Sweep do
  @shortdoc "Property sweep over plugin-activation subsets (static or on-device)"
  @moduledoc """
  The property sweep — generate plugin-activation subsets and check invariants
  across the combination space, shrinking failures to the minimal offending set.

      mix ci.sweep --static            # cheap: cross_validate soundness over the fixture space
      mix ci.sweep --runs 4            # device: 4 sampled subsets through P1–P11 + shrink
      mix ci.sweep --static --set all --versions hex     # minimal conflicting cores of a real set
      mix ci.sweep --runs 4 --set demo --versions master # device sweep on a generated host

  ## Modes

    * `--static` — generate subsets and verify `cross_validate` flags a conflict
      iff the subset actually collides. Milliseconds, no farm. Exit non-zero if
      any inconsistency is found (a validator soundness bug), each minimized.
      With a cell (`--set`/`--versions`) the pool is the set's real plugins at
      the row's versions and there is no collision oracle: the sweep instead
      reports every minimal subset `cross_validate` rejects (the pairs that
      can't be activated together), exit non-zero if there are any.

    * default (device) — run `--runs N` (default 4) sampled subsets of the
      device pool through the full catalog on one reused harness + container, and
      shrink any failing subset to its minimal core. Self-starts distribution (so
      a plain `mix ci.sweep --runs N` works — no `elixir --name` wrapper needed)
      and exits non-zero if any sampled subset fails or errors. Expensive (one
      build per activation switch) — best scheduled in a low-traffic window.
      With a cell the host is generated by the row's mob_new (`MobCi.Host`) with
      the whole set as deps, and every result carries the set name + versions.
  """
  use Mix.Task

  alias MobCi.{Cell, Dist, Sweep}

  @switches [
    static: :boolean,
    runs: :integer,
    count: :integer,
    set: :string,
    versions: :string,
    fresh: :boolean
  ]

  @impl Mix.Task
  def run(argv) do
    {opts, _, _} = OptionParser.parse(argv, switches: @switches)
    static? = opts[:static] == true or is_nil(opts[:runs])

    # The static sweep keeps the plugins parked in priv/sets/exclusions.exs in
    # the pool (the collision that parked them must stay visible); device
    # sweeps build hosts, so they leave them out.
    cell = if opts[:set] || opts[:versions], do: Cell.plan!(opts[:set], opts[:versions], include_excluded: static?)
    if cell, do: Mix.shell().info(Cell.describe(cell))

    cond do
      cell && opts[:static] -> static_cell(cell, opts)
      cell && is_nil(opts[:runs]) -> static_cell(cell, opts)
      opts[:static] or is_nil(opts[:runs]) -> static(opts)
      cell -> device(cell: cell, runs: opts[:runs], fresh: opts[:fresh] == true)
      true -> device(runs: opts[:runs])
    end
  end

  defp device(sweep_opts) do
    Dist.ensure!(:"mob_ci_sweep@127.0.0.1")

    case Sweep.device_sweep(sweep_opts) do
      {:error, reason} ->
        Mix.shell().error("device sweep could not start: #{inspect(reason)}")
        exit({:shutdown, 2})

      %{ran: ran} = summary ->
        Mix.shell().info("\n" <> Sweep.summarize(summary))
        failed = Enum.count(ran, fn {_subset, {v, _}} -> v in [:fail, :error] end)

        if failed > 0 do
          Mix.shell().error("device sweep: #{failed}/#{length(ran)} sampled subset(s) failed.")
          exit({:shutdown, 1})
        else
          Mix.shell().info("device sweep: all #{length(ran)} sampled subset(s) green.")
        end
    end
  end

  defp static(opts) do
    findings = Sweep.static_findings(count: Keyword.get(opts, :count, 300))

    if findings == [] do
      Mix.shell().info("✓ static sweep: cross_validate is sound over the sampled subset space.")
    else
      Mix.shell().error("✗ static sweep found #{length(findings)} inconsistency(ies):")

      for f <- findings do
        Mix.shell().error(
          "  minimal #{inspect(f.minimal)} — cross_validate=#{f.cross_validate}, colliding=#{f.colliding}"
        )
      end

      exit({:shutdown, 1})
    end
  end

  defp static_cell(cell, opts) do
    cores = Sweep.static_conflicts(pool: cell.plugins, count: Keyword.get(opts, :count, 300))

    if cores == [] do
      Mix.shell().info(
        "✓ static sweep: every sampled subset of #{cell.set} composes (cross_validate)."
      )
    else
      Mix.shell().error(
        "✗ static sweep: #{length(cores)} minimal conflicting core(s) in #{cell.set}:"
      )

      for core <- cores, do: Mix.shell().error("  #{inspect(core)}")
      exit({:shutdown, 1})
    end
  end
end
