# Generated by `mix ci.sets --regen` — do not edit. A greedy pairwise covering
# array (strength 2) over the buildable first-party plugins: every pair of
# plugins appears together, each alone, and both absent in some row.
# `test/mob_ci/sets_test.exs` fails when this drifts from the pool.
%{
  plugins: [:mob_ash, :mob_audio_capture, :mob_background, :mob_biometric,
   :mob_bluetooth, :mob_camera, :mob_deliver, :mob_location, :mob_midi,
   :mob_mishka, :mob_nfc, :mob_notify, :mob_photos, :mob_scanner,
   :mob_scene3d, :mob_screencast, :mob_sensors, :mob_sms, :mob_speech,
   :mob_touch, :mob_video, :mob_vision, :mob_wake, :mob_whisper],
  sets: [
    [:mob_ash, :mob_audio_capture, :mob_background, :mob_biometric,
     :mob_bluetooth, :mob_camera, :mob_deliver, :mob_location, :mob_midi,
     :mob_mishka, :mob_nfc, :mob_notify, :mob_photos, :mob_scanner,
     :mob_scene3d, :mob_screencast, :mob_sensors, :mob_sms, :mob_speech,
     :mob_touch, :mob_video, :mob_vision, :mob_wake, :mob_whisper],
    [:mob_ash],
    [:mob_audio_capture, :mob_biometric, :mob_camera, :mob_location,
     :mob_mishka, :mob_notify, :mob_scanner, :mob_screencast, :mob_sms,
     :mob_touch, :mob_vision, :mob_whisper],
    [:mob_background, :mob_bluetooth, :mob_deliver, :mob_midi, :mob_nfc,
     :mob_photos, :mob_scene3d, :mob_sensors, :mob_speech, :mob_video,
     :mob_wake],
    [:mob_ash, :mob_audio_capture, :mob_background, :mob_camera, :mob_deliver,
     :mob_mishka, :mob_nfc, :mob_scanner, :mob_scene3d, :mob_sms, :mob_speech,
     :mob_vision, :mob_wake],
    [:mob_ash, :mob_background, :mob_biometric, :mob_bluetooth, :mob_location,
     :mob_midi, :mob_notify, :mob_photos, :mob_screencast, :mob_sensors,
     :mob_touch, :mob_video, :mob_whisper],
    [:mob_ash, :mob_biometric, :mob_bluetooth, :mob_camera, :mob_deliver,
     :mob_midi, :mob_nfc, :mob_notify, :mob_scanner, :mob_sensors,
     :mob_speech, :mob_touch, :mob_vision],
    [:mob_ash, :mob_audio_capture, :mob_deliver, :mob_location, :mob_midi,
     :mob_mishka, :mob_photos, :mob_scene3d, :mob_screencast, :mob_sms,
     :mob_video, :mob_wake, :mob_whisper],
    [:mob_ash, :mob_audio_capture, :mob_background, :mob_biometric,
     :mob_bluetooth, :mob_camera, :mob_location, :mob_mishka, :mob_nfc,
     :mob_notify, :mob_photos, :mob_scanner, :mob_scene3d, :mob_screencast,
     :mob_sensors, :mob_video],
    [:mob_ash, :mob_background, :mob_midi, :mob_mishka, :mob_notify,
     :mob_scanner, :mob_screencast, :mob_sensors, :mob_sms, :mob_speech,
     :mob_touch, :mob_video, :mob_vision, :mob_wake, :mob_whisper],
    [:mob_ash, :mob_audio_capture, :mob_background, :mob_biometric,
     :mob_bluetooth, :mob_camera, :mob_deliver, :mob_location, :mob_midi,
     :mob_nfc, :mob_photos, :mob_scene3d, :mob_sms, :mob_speech, :mob_touch,
     :mob_vision, :mob_wake, :mob_whisper]
  ]
}
